### PR TITLE
Enhance testing on CI, fix #181

### LINKED ISSUE #181: Increased test coverage on CI
It might now be feasible to run a lot more of the unit tests on GitHub Actions, because the CBC solver can solver problems relatively quickly. This would have the benefit of greater cross-platform testing and potentially reduces chances of bugs. I could create a PR that replaces the `skip_on_ci()` skips in the unit tests with `skip_if_not_installed("rcbc")`? This would not affect the unit tests that CRAN runs, since the relevant unit tests would still contain `skip_on_cran()`? @ricschuster, what do you think? The downside is that individual CI runs will likely longer to complete.

### PR DESCRIPTION
**Pull request by jeffreyhanson**
I've updated the unit tests so that all the tests that involve generating solutions are now run on GitHub Actions (using rcbc). Unfortunately, it doesn't install on the R-devel services because it uses deprecated functionality (see ). I can't seem to get rcbc installed on Windows GitHub Actions runs either. Apart from that though (i.e. r-release on Ubuntu and Mac OSX), the unit tests seem to be all working. @ricschuster, can you take a look and let me know what you think?

### CODE REVIEW

**Comment by ricschuster** [comment]
Will have a look at the PR later today.

In the meantime, have you tried installing `rcbc` on a Windows machine yet? I haven't, but maybe that's something we should try. Would be nice if Windows users could use `rcbc`.

**Comment by jeffreyhanson** [comment]
Yeah - that's a good idea. I'll take a look at this after the new benchmark issue.

**Comment by jeffreyhanson** [comment]
Ok - I fixed the broken test. @ricschuster, this should be ready to merge when you're happy with it?

**Review by ricschuster — APPROVED** [review]
Thanks very much for enhancing the testing on CI Jeff!
I've only looked over the code quickly, but all looks good to me and as all checks pass, I'm going to merge the pull request back into master now.

**Pull request merged**
