### PR TITLE
update timing methods

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR updates and standardizes the methods for reporting solver run times. @ricschuster, can you take a look and see what you think? Is this consistent with how you are calculating run times manually when testing the benchmarks?

The main changes are in the solver R files (i.e. `R/add_lpsymphony_solver.R`,  `R/add_rsymphony_solver.R`,  `R/add_gurobi_solver.R`,  `R/add_cbc_solver.R`, `R/add_cplex_solver.R`).

### CODE REVIEW

**Comment by ricschuster** [comment]
Thanks very much Jeff!
Do you think this will make a difference for the benchmark runs?
The way you've set things up is consistent with what I'm usually doing, I just wonder if that will actually make a difference for the benchmarking?

I guess we can try and see?

**Comment by jeffreyhanson** [comment]
No - I don't think this would make any difference. But I could be wrong. I guess it's useful to rule out possible causes? Should I merge this now and update the benchmark packrat version?

**Comment by ricschuster** [comment]
Sounds good. Thanks!

**Comment by jeffreyhanson** [comment]
Ok will do

**Pull request merged**
