### PR TITLE
Make assertions on sparseMatrix memory safer

### PR DESCRIPTION
**Pull request by mstrimas**
avoid out of memory issue with assertions when using sparseMatrix input, issue #164

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Thank you very much for making this PR. It seems like this particular change might be causing the automated tests to fail (https://api.travis-ci.org/v3/job/739653475/log.txt) - is that right? 

I suspect this issue might be because the [method](https://github.com/prioritizr/prioritizr/blob/9708b273a8ee55a167463353123f339d771397e6/R/problem.R#L783-L788) is designed to accept both `matrix` and `dgCMatrix` (i.e. sparse matrix class objects) and, after verifying that they are valid, [converts them to `dgCMatrix` if needed](https://github.com/prioritizr/prioritizr/blob/9708b273a8ee55a167463353123f339d771397e6/R/problem.R#L831-L839). So, I suspect that putting `x@x` in the code for verifying the objects will cause incompatibility issues with base `matrix` input data?

So, one way to address this could be to remove this line:

```
      all(vapply(rij_matrix, function(x) sum(is.finite(x)), numeric(1)) > 0),
```

and add something like this after the first round of tests (e.g. place this code at [line 816](https://github.com/prioritizr/prioritizr/blob/9708b273a8ee55a167463353123f339d771397e6/R/problem.R#L816))

```
assertthat::assert_that(
  all(vapply(rij_matrix, FUN.VALUE = logical(1), function(x) {
    all(is.finite(c(min(x. na.rm = FALSE), max(x. na.rm = FALSE))))
  })),
  msg = "argument to x contains missing (NA) or non-finite (Inf) values")
```

What do you think? Could you please verify if calling `min` and `max` on a sparse matrix object won't involve converting it to a base matrix object? Maybe there's a simpler way to do this?

**Comment by mstrimas** [comment]
Oops, I made that change last week, works fine with the large `rij_matrix`, but unit tests failed and I forgot to come back to it. Going to work on this again today.

**Comment by mstrimas** [comment]
Ok, so the initial assertion was checking that at least one matrix value was finite:

```
# original
all(vapply(rij_matrix, function(x) sum(is.finite(x)), numeric(1)) > 0)
# my first attempt to fix this
all(vapply(rij_matrix, function(x) sum(is.finite(x@x)), numeric(1)) > 0)
```

But the one you proposed was checking that none of the matrix values were NA:

```
 all(vapply(rij_matrix, FUN.VALUE = logical(1), function(x) {
    all(is.finite(c(min(x. na.rm = FALSE), max(x. na.rm = FALSE))))
  }))
```

Which was causing unit tests to fail since some examples have NA matrix values. Fixed this assertion to go back to the original intention and now passes all unit tests locally and works on large `rij_matrix` objects.

**Comment by jeffreyhanson** [comment]
Ah - yeah that's right! Thank you for catching that @mstrimas!

**Comment by jeffreyhanson** [comment]
@mstrimas, if you install this branch on your system, does prioritizr work with the large sparse matrices? If so, we can merge this into the master branch.

**Comment by mstrimas** [comment]
Works perfectly! Just merged to master.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Pull request merged**
