### PR TITLE
Evaluate solutions

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR adds functionality to evaluate solutions according to various metrics (#161). It also fixes the NEWS issue (#173) and compatibility with the new Matrix package version (#172). @ricschuster, when you get a chance, could you please take a look? 

I've also been thinking some more about the best way to consistently name functions for evaluating solutions and would appreciate your input? In #161, we talked about adding a suffix (e.g. `_summary` or `_statistic`) to be consistent with the other functions in prioritizr (e.g. functions adding targets have a `_targets` suffix). But I was wondering if there is a better approach? I realized/noticed/remembered that the existing functions for customizing problem objects all start with an `add_` prefix (e.g. `add_relative_targets`) that (hopefully?) serves as useful cue as to the intended purpose of the function (i.e. the `add_relative_targets` function is meant to be "added" to a problem object and this is hinted with the "add" prefix). So, given this idea/logic/format, I thought it might be useful to give the solution evaluation functions a prefix? What do you think? I've written the named the functions using the  `eval_` prefix  (e.g. `eval_cost` function calculates the cost of a solution), because typing `evaluate_` might get a bit annoying after a while? What do you think? I haven't given the solution evaluation functions a suffix, but maybe this would make more sense (e.g. `eval_cost_statistic` or `eval_cost_summary`)?

I'm just realizing this now (as I type this), but I wonder if there is an argument to be made that the irreplaceability functions (e.g. `ferrier_score`) should also a more standardized naming convention. Perhaps these functions should start with the `eval_` prefix too? Maybe we could distinguish between the "summary" type and "irreplaceability" type functions using a  standardized suffix (e.g. `eval_cost_statistic` for calculating solution costs and `eval_ferrier_importance` for evaluating the importance/irreplaceability of planning units in a solution)? Thoughts? I find "irreplaceability" really annoying to type so I would suggest against putting that in function names.

The main stuff is in the files:
* New section in vignette for evaluating solutions (see Evaluating solutions section in `vignettes/prioritizr.Rmd`)
* Manual entry for evaluating solutions (`R/evaluation.R`)
* Calculating the number of planning units selected in a solution (`R/eval_n.R`, `tests/testthat/test_eval_n.R`)
* Calculating solution cost (`R/eval_cost.R`, `tests/testthat/test_eval_cost.R`)
* Calculating exposed boundary (perimeter) length of a solution (`R/eval_boundary.R`, `tests/testthat/test_eval_boundary`).
* Calculating overall connectivity of a solution (`R/eval_connectivity.R`, `tests/testthat/test_eval_connectivity.R`)
* Calculating feature representation (`R/eval_feature_representation.R`, `tests/testthat/test_eval_feature_representation.R`)
* Calculating target coverage (`R/eval_target_coverage.R`, `tests/testthat/test_target_coverage.R`)

### CODE REVIEW

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson 
Will have a look at this now.

Before I start: in response to your function name thoughts above, I agree with you on the prefix suggestion.
I think using `eval_` makes a lot of sense.

As for irreplacability, I agree that using that term in a function name would not be ideal.
What do you think about the following naming convention:

First prefix = `eval`
Second prefix = what should be evaluated (e.g. `cost`, `importance`, ...)
Finally, function name or statistic to be produced (e.g. `summary`, `replecement_cost`, `ferrier_score`,...)

What do you think about that idea?

**Comment by jeffreyhanson** [comment]
Awesome - thanks! 

Ok - great. Glad to hear that the `eval_` prefix makes sense (I find naming things really difficult). Just to clarify, would that naming scheme rename the `eval_cost` function (i.e. calculate cost of a solution) to `eval_summary_cost` and `ferrier_score` to `eval_importance_ferrier_score`? Or are you suggesting `eval_cost_summary` and `eval_ferrier_score_importance`? In my mind, the "summary" (or "statistic") component of the name would occupy the same "position" (or index) in the function name as "importance" to be consistent?

I'll include all the relevant functions below so we can see how they would look (old -> new). If I've misunderstood your format, could you please copy the correct format into a new post?

* `eval_cost` -> `eval_summary_cost`
* `eval_boundary` -> `eval_summary_boundary`
* `eval_connectivity` -> `eval_summary_connectivity`
* `eval_n` -> `eval_summary_n`
* `eval_feature_representation` -> `eval_summary_feature_representation`
* `eval_target_coverage` -> `eval_summary_target_coverage`
* `ferrier_score` -> `eval_importance_ferrier` (I suggest we drop "score" to reduce name length)
* `replacement_cost` -> `eval_importance_replacement`  (I suggest we drop "cost" to reduce name length)
* `rarity_weighted_richness` -> `eval_importance_rwr`  (I suggest we use an acronym to reduce name length)

**Comment by ricschuster** [comment]
I do like the new format and it is in line with what I was thinking.
It works well for importance I think.

For the rest, what do you think about something like this?
Might be too messy though?

- `eval_cost` -> `eval_summarise_cost`
- `eval_boundary` -> `eval_summarise_boundary`
- `eval_connectivity` -> `eval_summarise_connectivity`
- `eval_n` -> `eval_summarise_n`
- `eval_feature_representation` -> `eval_representation_feature`
- `eval_target_coverage` -> `eval_coverage_target`

I'm no good at this. Maybe summarise is weird and summary works better?
For `feature_representation` and `target_coverage` I just tried to emulate the naming convention of other parts, but maybe that doesn't work well in this case.
What do you think about using either `representation` or `coverage` for both features and targets?
(I think I like `representation` better)

**Comment by jeffreyhanson** [comment]
Hmm, I think we would want to keep the "summarize"/"summary"/"statistic" component in the name for the `eval_feature_representation` and `eval_target_representation` to be consistent with other functions designed to calculate statistics/summarize solutions.

Yeah, summarise does look a bit odd. Plus it potentially adds annoyance with differences between US/UK English.

Good question about `eval_tagret_coverage` vs. `eval_feature_representation`. My understanding is that the term "representation" is always used to describe how well features are covered by a prioritization. Although targets are used to help decide if features are adequately represented, we do not actually measure how well targets themselves are represented by a prioritization. Thus a different term (e.g. coverage or something else?) is needed. What do you think?

**Comment by ricschuster** [comment]
I think you are right. Lets go with the 'new' suggestions you made above. I think they are good.

**Comment by ricschuster** [comment]
For `eval_boundary` do you think it would make sense for multi-zone problems to report the total perimeter as well?
At this point boundaries are zone specific, but I wonder if it might be useful to also report the value of the total perimeter of a solution regardless of zones? Do you think that would make sense and be useful? 

If I imagine I have a number of management action I want to implement, it might be useful for me to know the total perimeter of the area that I am prioritizing. This assumes there might be some benefit of different actions being in spatial proximity.

Maybe its such a special use case that we don't need to include at this point?

**Comment by jeffreyhanson** [comment]
Hmm, I wonder if adding "summary"/"importance" at the end would be more consistent (e.g. like how we have `add_relative_targets` and not `add_targets_relative`). So what about this:

* `eval_cost` -> `eval_cost_summary`
* `eval_boundary` -> `eval_boundary_summary`
* `eval_connectivity` -> `eval_connectivity_summary`
* `eval_n` -> `eval_n_summary`
* `eval_feature_representation` -> `eval_feature_representation_summary`
* `eval_target_coverage` -> `eval_target_coverage_summary`
* `ferrier_score` -> `eval_ferrier_importance`
* `replacement_cost` -> `eval_replacement_importance`
* `rarity_weighted_richness` -> `eval_rwr_importance`

How does that sound?

**Comment by ricschuster** [comment]
For `eval_target_coverage`, what do you think about replacing output column `absolute_shortfall` (and `relative_shortfall`) which a column that shows the value distance to the target? We we do this, a user gets a sense of how far better than the absolute target the solution performs. If we stick with the shortfall = positive number approach, we could report negative numbers for solutions that surpass the target.

What do you think? With the `relative_` columns its easy to see if a solution surpasses targets, but with the `absolute_` columns it would be harder to see from `_target` and `_held`.

**Comment by ricschuster** [comment]
> Hmm, I wonder if adding "summary"/"importance" at the end would be more consistent (e.g. like how we have `add_relative_targets` and not `add_targets_relative`). So what about this:
> 
>     * `eval_cost` -> `eval_cost_summary`
> 
>     * `eval_boundary` -> `eval_boundary_summary`
> 
>     * `eval_connectivity` -> `eval_connectivity_summary`
> 
>     * `eval_n` -> `eval_n_summary`
> 
>     * `eval_feature_representation` -> `eval_feature_representation_summary`
> 
>     * `eval_target_coverage` -> `eval_target_coverage_summary`
> 
>     * `ferrier_score` -> `eval_ferrier_importance`
> 
>     * `replacement_cost` -> `eval_replacement_importance`
> 
>     * `rarity_weighted_richness` -> `eval_rwr_importance`
> 
> 
> How does that sound?

Great point. Lets go with that.

**Comment by jeffreyhanson** [comment]
Also, excellent question about how we should handle zone stuff. At the moment, I have written the `eval_*_summary` functions to output a tibble reporting the "overall" summary (e.g. overall exposed boundary length across all zones, parametrised per zones arguments) and also a summary for each different zone (e.g. exposed boundary length for each different zone). For problems with only a single zone, then only the "overall" summary is shown. For example, see `docs/reference/add_boundary_penalties.html` in the eval branch.

**Comment by jeffreyhanson** [comment]
Ok, I'll update the function names now.

**Comment by jeffreyhanson** [comment]
> > Hmm, I wonder if adding "summary"/"importance" at the end would be more consistent (e.g. like how we have `add_relative_targets` and not `add_targets_relative`). So what about this:
> > ```
> > * `eval_cost` -> `eval_cost_summary`
> > 
> > * `eval_boundary` -> `eval_boundary_summary`
> > 
> > * `eval_connectivity` -> `eval_connectivity_summary`
> > 
> > * `eval_n` -> `eval_n_summary`
> > 
> > * `eval_feature_representation` -> `eval_feature_representation_summary`
> > 
> > * `eval_target_coverage` -> `eval_target_coverage_summary`
> > 
> > * `ferrier_score` -> `eval_ferrier_importance`
> > 
> > * `replacement_cost` -> `eval_replacement_importance`
> > 
> > * `rarity_weighted_richness` -> `eval_rwr_importance`
> > ```
> > 
> > 
> > How does that sound?
> 
> Great point. Lets go with that.

Ok, I'll update the function names now.

**Comment by ricschuster** [comment]
> Also, excellent question about how we should handle zone stuff. At the moment, I have written the `eval_*_summary` functions to output a tibble reporting the "overall" summary (e.g. overall exposed boundary length across all zones, parametrised per zones arguments) and also a summary for each different zone (e.g. exposed boundary length for each different zone). For problems with only a single zone, then only the "overall" summary is shown. For example, see `docs/reference/add_boundary_penalties.html` in the eval branch.

I saw that and think its great. Was just wondering if you think there would be a use for the additional row in the output that I had in mind with the question? Not sure if that would actually be of much use, but worth thinking about I figured.

**Comment by ricschuster** [comment]
Pushed a few text changes from reading through the new function documentation.

**Comment by jeffreyhanson** [comment]
> > Also, excellent question about how we should handle zone stuff. At the moment, I have written the `eval_*_summary` functions to output a tibble reporting the "overall" summary (e.g. overall exposed boundary length across all zones, parametrised per zones arguments) and also a summary for each different zone (e.g. exposed boundary length for each different zone). For problems with only a single zone, then only the "overall" summary is shown. For example, see `docs/reference/add_boundary_penalties.html` in the eval branch.
> 
> I saw that and think its great. Was just wondering if you think there would be a use for the additional row in the output that I had in mind with the question? Not sure if that would actually be of much use, but worth thinking about I figured.

Hmm - the `zones` argument tells the `eval_boundary_summary` function how to treat adjacent planning units that are allocated to different zones (exactly same as `zones` argument in `add_boundary_penalties`). So,  we could calculate this by using a `zones` argument with a matrix containing 1s in all cells. What name would give this value?

**Comment by jeffreyhanson** [comment]
> Pushed a few text changes from reading through the new function documentation.

Awesome - thanks!

**Comment by ricschuster** [comment]
> Hmm - the `zones` argument tells the `eval_boundary_summary` function how to treat adjacent planning units that are allocated to different zones (exactly same as `zones` argument in `add_boundary_penalties`). So, we could calculate this by using a `zones` argument with a matrix containing 1s in all cells. What name would give this value?

That would be great. As for the name, I have no idea. 
`cross_zone_perimeter`?
I'm really bad at this.

**Comment by jeffreyhanson** [comment]
> For `eval_target_coverage`, what do you think about replacing output column `absolute_shortfall` (and `relative_shortfall`) which a column that shows the value distance to the target? We we do this, a user gets a sense of how far better than the absolute target the solution performs. If we stick with the shortfall = positive number approach, we could report negative numbers for solutions that surpass the target.
> 
> What do you think? With the `relative_` columns its easy to see if a solution surpasses targets, but with the `absolute_` columns it would be harder to see from `_target` and `_held`.

Hmm, good question. I think the main difficulty with this function is making sure it (1) outputs numbers that are easy for users to understand and (2) outputs numbers that are useful for the user. To achieve (1), I think it might be useful to report shortfalls the same way that Marxan does? My understanding is shortfall calculations in `eval_target_coverage` follow the same method as Marxan (but generalized to different target sense values)?

I agree that it can be tricky to see if the targets are met when just looking at the numbers, so the function also has a `met` column (`logical` indicating if target is met or not). Maybe the real issue here is that the met column is last, so it gets cut off from the default print.tbl_df method. So, to address this issue, what if we put the `met` column before the `total_amount` column so it can easily be seen?

**Comment by ricschuster** [comment]
> Hmm, good question. I think the main difficulty with this function is making sure it (1) outputs numbers that are easy for users to understand and (2) outputs numbers that are useful for the user. To achieve (1), I think it might be useful to report shortfalls the same way that Marxan does? My understanding is shortfall calculations in `eval_target_coverage` follow the same method as Marxan (but generalized to different target sense values)?
> 
> I agree that it can be tricky to see if the targets are met when just looking at the numbers, so the function also has a `met` column (`logical` indicating if target is met or not). Maybe the real issue here is that the met column is last, so it gets cut off from the default print.tbl_df method. So, to address this issue, what if we put the `met` column before the `total_amount` column so it can easily be seen?

I agree, reporting shortfalls the same way Marxan does would be useful.
Good point re: column order. Putting the `met` column before the `total_amount` column sounds good to me, thanks.

**Comment by jeffreyhanson** [comment]
> > Hmm - the `zones` argument tells the `eval_boundary_summary` function how to treat adjacent planning units that are allocated to different zones (exactly same as `zones` argument in `add_boundary_penalties`). So, we could calculate this by using a `zones` argument with a matrix containing 1s in all cells. What name would give this value?
> 
> That would be great. As for the name, I have no idea.
> `cross_zone_perimeter`?
> I'm really bad at this.

Hmm, ideally we would also report such a statistic for the other `eval_*_summary` functions too (or at least the connectivity function too). So I don't think including a term like perimeter would generalize well for other functions. We could use something like "total" or "entire" -- but I worry that such a name would easily be confused with "overall" (which explicitly considers how different zones are treated). What if we included an example showing how to calculate "total" (for lack of a better term) perimeter of a multiple zone solution (using the all 1s matrix)?

**Comment by jeffreyhanson** [comment]
Just to check, is it OK if I start implementing all these changes now? Or were there more commits you wanted to make first? Either works for me - I just don't want to deal with a merge conflict.

**Comment by ricschuster** [comment]
Okay for you to get started with changes now. I will hold off making further edits. I was pretty much done anyways.

**Comment by ricschuster** [comment]
> Hmm, ideally we would also report such a statistic for the other `eval_*_summary` functions too (or at least the connectivity function too). So I don't think including a term like perimeter would generalize well for other functions. We could use something like "total" or "entire" -- but I worry that such a name would easily be confused with "overall" (which explicitly considers how different zones are treated). What if we included an example showing how to calculate "total" (for lack of a better term) perimeter of a multiple zone solution (using the all 1s matrix)?

I was thinking about `total` or `entire` as well and saw the same issues that you raised here. 
The example route sounds good to me. Maybe mention this in the function documentation as well to make sure interested users will look all the way through the examples?

**Comment by jeffreyhanson** [comment]
> > Hmm, ideally we would also report such a statistic for the other `eval_*_summary` functions too (or at least the connectivity function too). So I don't think including a term like perimeter would generalize well for other functions. We could use something like "total" or "entire" -- but I worry that such a name would easily be confused with "overall" (which explicitly considers how different zones are treated). What if we included an example showing how to calculate "total" (for lack of a better term) perimeter of a multiple zone solution (using the all 1s matrix)?
> 
> I was thinking about `total` or `entire` as well and saw the same issues that you raised here.
> The example route sounds good to me. Maybe mention this in the function documentation as well to make sure interested users will look all the way through the examples?

Ok great - excellent idea! I'll add that to the docs

**Comment by jeffreyhanson** [comment]
> > > Hmm, I wonder if adding "summary"/"importance" at the end would be more consistent (e.g. like how we have `add_relative_targets` and not `add_targets_relative`). So what about this:
> > > ```
> > > * `eval_cost` -> `eval_cost_summary`
> > > 
> > > * `eval_boundary` -> `eval_boundary_summary`
> > > 
> > > * `eval_connectivity` -> `eval_connectivity_summary`
> > > 
> > > * `eval_n` -> `eval_n_summary`
> > > 
> > > * `eval_feature_representation` -> `eval_feature_representation_summary`
> > > 
> > > * `eval_target_coverage` -> `eval_target_coverage_summary`
> > > 
> > > * `ferrier_score` -> `eval_ferrier_importance`
> > > 
> > > * `replacement_cost` -> `eval_replacement_importance`
> > > 
> > > * `rarity_weighted_richness` -> `eval_rwr_importance`
> > > ```
> > > 
> > > 
> > > How does that sound?
> > 
> > 
> > Great point. Lets go with that.
> 
> Ok, I'll update the function names now.

I just realized that `_summary` could cause issues. The prioritizr documentation includes a help page for each "group" of functions. For example, the `?targets` help page describes different target functions (e.g. `add_absolute_targets()`, `add_relative_targets()`), and the `?decisions` help page describes different decision functions (e.g. `add_binary_decisions()`, `add_proportion_decisions()`). So, if we use the `eval_*_summary` format then the corresponding help page would be `?summary` -- which would cause conflicts with the base R summary help page and also the summary help page in prioritizr for showing object summaries. To avoid these issues, I suggest we pick a different suffix. How do you feel about `_statistic` as a suffix?

**Comment by jeffreyhanson** [comment]
Oh actually, since we're using a plural for the help page (e.g. targets, decision, etc). The help page should be named "summaries" -- so that won't cause any issues.

**Comment by jeffreyhanson** [comment]
I've finished implementing the changes we talked about. @ricschuster, could you please take a look again and let me know what you think?

Specifically, I've renamed all the summary + importance score functions to be more consistent. Also, I've updated the docs  (e.g. including a "Data format" section for all functions where relevant) to be more consistent too (previously this information was crammed into the "Details" section which wasn't very well organized). I've added the "total" boundary length example you suggested too (see `eval_boundary_summary()` documentation). Since it seemed like a lot of the "useful" parts of the examples were obscured by solver log information, I've  updated the examples to avoid printing solver information (i.e. setting `verbose = FALSE`) . How does that sound? Have I missed anything?

The main changes (from the previous eval branch version you looked at) are:

* Vignette section for solution summaries and importance score  (prioritizr.Rmd)
* README (now has examples for calculating cost + target coverage)
* Manual entry for solution summaries (R/summaries.R)
* Example for calculating exposed boundary (perimeter) length of a solution (R/eval_boundary_summary.R,).
* Importance score documentation (R/importance.R, R/eval_ferrier_importance.R, R/eval_replacement_importance.R, R/eval_rare_richness_importance.R)
* Documentation for targets, constraints, and penalties (R/*_targets.R, R/*_constraints.R, R/*_penalties.R)

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson !
I've finished going through the changes and I like them a lot. 

Thanks very much for adding the 'overall exposed boundary' example.

The change to the documentation structure really helps make the docs more organized and will hopefully help users find the information they are looking for even easier now.

If you don't have anymore additions to this branch, we can merge it back into main.

**Comment by jeffreyhanson** [comment]
Ok brilliant - thanks! Yeah, I think this is ready to be merged - I'll it merge now.

**Pull request merged**
