### PR TITLE
update asymmetric connectivity

### PR DESCRIPTION
**Pull request by jeffreyhanson**
Hi @ricschuster,

I've been helping @eleanorstewart17 with some prioritizr issues. As part of this, we realized that the `add_connectivity_penalties()` function doesn't treat asymmetric connectivity the same way as _Marxan_. So, this PR adds functionality to generate and evaluate prioritizations with asymmetric connectivity data using the same mathematical formulation as _Marxan_. To acheive this, I've added new penalty function (`add_asym_connectivity_penalties()`) for generating prioritizations with asymmetric connectivity data. I have also created a new `eval_asym_connectivity_summary()` function for measuring the overall connectivity faciliated by a prioritization using the same calculations as _Marxan_. Also, I've updated `add_connectivity_penalties()` and `eval_connectivity_summary()` so that they will now only work with symmetric connectivity data.

I also updated `presolve_check()` to recognize potential numerical issues arising from values in the asymmetric connectivity data. I also took this opportunity to update the function to prevent it from throwing meaningless warning when the objective function only contains zeros.

We also realized that the code used to work with connectivity data stored in `data.frame` format did not always handle asymmetric data correctly (i.e., it sometimes incorrectly treated it as symmetric data). To address this, I've created a new `marxan_connectivity_data_to_matrix()` function so that users can explicitly specify whether connectivity data should be symmetric or asymmetric (using the `symmetric` parameter). Additionally, with this new function, I've updated the `marxan_problem()` function so that users can import and solve problems with asymmetric connectivity data.

When you get a chance, could you please take a look through the updated files and let me know what you think?

The relevant files in this PR are:

* **R/add_asym_connectivity_penalties.R:** definition/documentation of new penalties function.
* **src/rcpp_add_asym_connectivity_penalties.cpp:**: underying C++ code to apply new penalty.
* **tests/testthat/test_add_asym_connectivity_penalties.R**: tests for new penalties function.
* **R/eval_asym_connectivity_summary.R:** definition/documentation of new evaluation function.
* **src/rcpp_asym_connectivity.cpp:**: underying C++ code for new evaluation function.
* **tests/testthat/test_eval_asym_connectivity_summary.R**: tests for new evaluation function.
* **R/add_connectivity_penalties.R:** code/documentation updates for working only with symmetric connectivity.
* **R/marxan_connectivity_data_to_matrix.R:** code/documentation for new conversion function.
* **tests/testthat/marxan_connectivity_data_to_matrix.R:** tests for new conversion function.
* **R/marxan_boundary_data_to_matrix.R:** code/documentation for new conversion function.
* **R/penalties.R:** update documentation for `add_asym_connectivity_penalties()` and `eval_connectivity_penalties()`.
* **R/summaries.R:** update documentation for `eval_asym_connectivity_summary()` and `eval_connectivity_summary()`.
* **vignette/package_overview.Rmd:** update vignette with `add_asym_connectivity_penalties()` , `add_connectivity_penalties()` , `eval_asym_connectivity_summary()` and `eval_connectivity_summary()`.
* **vignette/publication_record.Rmd:** add new publication and updates URLs to pass CRAN checks. It would seem that Wiley and Science have updated their websites so that CRAN checks consider the DOIs for some papers to resolve to broken URLs.

### CODE REVIEW

**Comment by ricschuster** [comment]
@jeffreyhanson I'd be happy to. Should I hold off for a bit as you are still pushing commits to this PR?

**Comment by jeffreyhanson** [comment]
@ricschuster - thanks for checking! I might just make a few more changes to improve test coverage. I'll let you know when it's ready.

**Comment by jeffreyhanson** [comment]
@ricschuster, sorry for the delay, could you please take a look now?

**Comment by ricschuster** [comment]
@jeffreyhanson I've only gone over some of the code so far, but given that I'm not likely to be able to have a closer look until next week, I would suggest we go ahead and merge the pull request so I don't slow you down. What do you think?

**Comment by jeffreyhanson** [comment]
@ricschuster, thanks for the heads up. Since this PR makes a bunch of changes, I think it's worth waiting till you've had a chance to go through it properly? In addition to the code changes, there's also a bunch of documentation changes, and I'd really appreciate your feedback on that too. How does that sound?

**Comment by ricschuster** [comment]
Sounds good to me. I will have a look as soon as I can.

**Comment by jeffreyhanson** [comment]
@ricschuster, I've just been sent a paper to add to the publication record, would you mind if I (i) added it to the vignette, and (ii) rebuilt the vignette html file + pkgdown website? Or would that interfere with any edits/changes you've made (I don't want to create merge conflicts to deal with)? I'm happy to add this later if that's easier - but I just thought I'd ask?

**Comment by ricschuster** [comment]
Please go ahead. I haven't started yet.

**Comment by jeffreyhanson** [comment]
Thanks - I've just updated the publication record vignette. I don't plan on making any further changes.

**Comment by ricschuster** [comment]
This all looks great and I only have a few small comments below (in addition to a slight wording change suggestion).

`R/add_connectivity_penalties.R`: on my machine 'Önal H, and Briers RA' renders as 'Ã–nal H, and Briers RA'

I'm not clear what the difference between `R/marxan_connectivity_data_to_matrix.R` and `R/marxan_boundary_data_to_matrix.R` is from their documentation. Is the first for asymmetric and the second for symmetric connectivity? If so, could you add more text making that clear? Would a name change made sense as well, e.g. to include 'asym'?

**Comment by jeffreyhanson** [comment]
Awesome - thank you @ricschuster! Thanks for catching that rendering issue, and yeah, the `marxan_connectivity_data_to_matrix()` has the ability to load symmetric and asymmetric data (controlled by a parameter). I'll update the docs to fix these issues.

**Comment by jeffreyhanson** [comment]
I'm having trouble reproducing the rendering issue with "Önal H, and Briers RA", could you please send me a screenshot?

**Comment by ricschuster** [comment]
Sure. I see the following if I do:
```
devtools::load_all(".")
?add_connectivity_penalties
```

image

**Comment by jeffreyhanson** [comment]
Ah ok - thanks! Interesting that it's happening on the HTML preview option (I have R configured on my computer so that it shows help pages on the terminal).

**Comment by jeffreyhanson** [comment]
@ricschuster, when you get a chance, could you please take a look and see if the prevous commit fixed it?

**Comment by ricschuster** [comment]
It did. Thanks Jeff!

**Comment by jeffreyhanson** [comment]
Brilliant - thanks for cheching! I'll merge this today then

**Pull request merged**
