### PR TITLE
remove shiny, fix #141

### LINKED ISSUE #141: remove shiny integration functionality
A lot of prioritizr's underlying functions have baked in shiny integration. This was originally implemented with the aim to make it easy to build a shiny interface for prioritizr. However, this shiny functionality (1) massively increases the installation footprint of prioritizr (i.e. users must install the shiny, xtable, and rhandsontable packages) and (2) does not actually appear to provide a useful interface for shiny applications (based on discussion with @ricschuster). Once @ricschuster has made more progress with the shiny app for prioritizr, confirming that existing shiny functionality aren't needed, we can go about removing the baked in shiny integration.

I'm making this issue so I don't forget. @ricschuster did I miss anything? Does that sound like a sensible plan?

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR removes shiny integration to remove unused dependencies (fix #141). @ricschuster, when you get a chance, can you take a look at it?

### CODE REVIEW

**Comment by ricschuster** [comment]
Thanks Jeff!
I've only made one tiny change, the rest looks good to me.

As you mention v7.0 in the readme, should we push to CRAN once the pull request is merged into master?

**Comment by jeffreyhanson** [comment]
Thanks for catching those mistakes! I'll pull your commits and rebuild the package website. Yeah, I think it's probably worth submitting a new version to CRAN soon. Are there any remaining issues that we want to address before we do that? It might be nice to add the solver benchmarking vignette. I'm hoping that I can finish the benchmark repo by the end of today, so if you've got some time to write up the benchmarking vignette in the prioritizr package over then next few days, then we could probably add that before the next CRAN release?

**Comment by jeffreyhanson** [comment]
Specifically, if we want to make any more version breaking changes, I suppose now is the best time since this already contains quite a few of them?

**Comment by ricschuster** [comment]
Good points. 
I think including the benchmarking results would be great for the next CRAN version.
The only other thing I can think of if BPF calibration. Not sure if you have any ideas of how to do this efficiently though?

**Comment by jeffreyhanson** [comment]
Yeah, it would be good to include some BPF calibration stuff. We could try include the zero cost method outlined in the Marxan Good Practices Handbook. This tries to find a a single penalty value that equally balances spatial fragmentation vs. cost. However, depending on the range of cost values, this will not necceasrily be good given "real-world" considerations.

**Comment by ricschuster** [comment]
Its a tough one. I agree with you that the MGPH method will not necessarily produce good results. Maybe its a good starting point though and we just need to make the point that you made in the documentation?

**Pull request merged**
