### PR TITLE
update data simulation functions

### PR DESCRIPTION
**Pull request by jeffreyhanson**
- removes RandomFields as dependency

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, when you get a chance, could you please review this PR? The main changes are in `R/simulate.R` and `tests/testthat/test_simulate.R`.

**Comment by jeffreyhanson** [comment]
Also, please ignore the failing codecov check - that's just saying that code coverage has decreased slightly because the total lines of code has decreased with this PR.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson!
I've looked over the PR and all looks good to me. Happy for you to merge the pull request.

**Comment by jeffreyhanson** [comment]
Awesome - thanks! I realized that the updated simulation code only really works for small rasters (e.g. less than 50 rows and 50 columns). Do you think it would be worth implementing an alternative that works for larger datasets? I managed to find a method for the aoh package that scales well for larger datasets, but it requires an additional dependency (i.e. the fields package). What do you think?

**Comment by ricschuster** [comment]
Unless you think its important to go beyond 50x50, I would say lets stick with what we have and don't add another dependency.

**Comment by jeffreyhanson** [comment]
Yeah, I don't think it's that important - the main point of this package isn't data simulation. Ok great - I'll merge the PR then. Thanks!

**Pull request merged**
