### PR TITLE
Version 8 updates

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This is PR is in draft form at the moment. I'll update when it's ready for review.

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, I think this is ready to reivew now. When you get a chance, could you please take a look? I've sent an email with some details/quesions, but feel free to follow up here or over email (which ever is easier for you).

**Comment by jeffreyhanson** [comment]
@ricschuster, I'm sorry, just found a bug in the new boundary length calculations. Please hold off on the review until I've got them working.

**Comment by ricschuster** [comment]
@jeffreyhanson thanks for the heads up. Once you are ready, should we invite 
@edwardsmarc to help with the code review?

**Comment by jeffreyhanson** [comment]
Yeah, sounds great! When it's ready for review, I'll repost the details from the email about what things to look out for in the review. If it would be helpful/useful, I'd be happy to have a meeting with @edwardsmarc to go over the package structure/organization?

**Comment by edwardsmarc** [comment]
Thanks @jeffreyhanson, @ricschuster and I discussed this this morning and agreed that a meeting to review package structure/organization would be useful. We also think that reviewing this large pull request might be too much for me until I'm more familiar with the package. Happy contribute where I can though!

**Comment by jeffreyhanson** [comment]
Ah ok - yeah, sounds good! Thanks! I'll send an email once it's ready, and include some possible suggestions for things that you might be able to help with (e.g., try running code with large input datasets to see how the updated functions scale, or reading through the docs to look for typos or bad writing), and we can take it from there? No worries if you're busy with other stuff - I completely understand.

**Comment by jeffreyhanson** [comment]
Sorry about the delay @edwardsmarc and @ricschuster, I think the PR is ready now. 

It turns out that the boundary calculations were correct, and the code I was using to "confirm" that the calculations were correct actually had a bug in them. Specifically, the CRAN version of `sf::st_as_sf()` can sometimes produce incorrect results when `SpatialPolygonDataFrame` objects have holes in them, this is fixed in the GitHub version of sf though.

Assuming I understand correctly, it sounds like @ricschuster is happy to do the code review, and both @edwardsmarc and @ricschuster might be able to help with some additional tasks/checks. Is that right? Sorry if I'm misunderstanding something. Assuming I have got that right, then here's some things that would be really helpful.

1.  It would be really helpful if someone could check that the error messages are formatted correctly, and contain informative error messages. I've overhauled how prioritizr handles error messages so that it now throws tidyverse/rlang style error messages with nice formatting (see below). However, if the code used to generate the error message isn't correct, then the message will say that the error occured in the wrong function (e.g., it might say something like `Error in .local()` when it should say `Error occured in problem()`) or it might say that it couldn't parse the error message (e.g., it might say something like `Could not evaluate cli expression`). For example, under the CRAN version of prioritizr produces the following error message:
    ```
    library(prioritizr)
    data(sim_pu_sf, sim_features)
    p1 <- 
      problem(sim_pu_polygons, features = sim_features, cost_column = "cost") %>%
      add_min_set_objective() %>%
      add_relative_targets(c(0.15, 0.1)) %>%
      add_binary_decisions() %>%
      add_gurobi_solver(gap = 0)
    #> Error: `%in%`(x = length(targets), table = c(1, number_of_features(x))) is not TRUE
    ```
    And the equivalent version 8 is now this. As you can see, it contains the name of the function where the error occurred (which is nice when using pipes), and a (hopefully) informative description of what went wrong:
    ```
    library(prioritizr)
    sim_pu_polygons <- get_sim_pu_polygons()
    sim_features <- get_sim_features()
    p1 <- 
      problem(sim_pu_polygons, features = sim_features, cost_column = "cost") %>%
      add_min_set_objective() %>%
      add_relative_targets(c(0.15, 0.1)) %>%
      add_binary_decisions() %>%
      add_gurobi_solver(gap = 0)
    #> Error in `add_relative_targets()`:
    #> ! `length(targets)` must be 1 or 5.
    #> Run `rlang::last_error()` to see where the error occurred.
    ```
2. It would be great if someone could try running the new version of prioritizr over a large raster dataset (i.e., one that doesn't all fit in RAM). In theory, it should be faster now that it uses terra and I've tried improving the `rij_matrix()` function, but it would be great to verify this. Note that the person testing this might want/need to try increase terra's gdal cache for best performance (see https://rdrr.io/cran/terra/man/gdal.html).
3. It would be extremely awesome if someone could read through the package documentation (e.g., the version of the website in the PR, which can be opened via `docs/index.html` file) and look for any typos or formatting issues. I've looked through it a few times now, but a second set of eyes would be really helpful.

How does that sound? @edwardsmarc, do you think you'd be able to help with any of these?

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson! I'm looking forward to testing this new version. I'm happy to do the code review and also focus on the bullets you mentioned, especially 1. and 2. 
@edwardsmarc would you be able to have a look at 1. and 3.?
No rush, but would be awesome to have you read over the documentation and provide your thoughts.
I guess if you find typos just fix them and add a commit here. What do you think @jeffreyhanson?

**Comment by edwardsmarc** [comment]
Yes, I can take on 3. And test 1. The timing is good for reviewing the documentation, I recently read through it all to learn prioritizr.

Just to confirm my workflow: I'll clone the repo, fetch everything, checkout branch v8 and commit changes to the vignette .Rmd files. I won't rebuild the html files.

@jeffreyhanson, I found a potential error when reading through the connectivity tutorial. Can you confirm that the line:
`salt_con_binary <- round(salt_con <= threshold_limit)`
should in fact be:
`salt_con_binary <- round(salt_con >= threshold_limit)`

**Comment by jeffreyhanson** [comment]
Yeah that all sounds great - thank you very much @edwardsmarc and @ricschuster! Just an idea, since you'll both be working on the package at the same time, would it be worth creating a new branch off this branch? This way, once you've finished all your changes, we can then merge them into this branch? This might help avoid merge conflicts (e.g. if you both edit the documentation forthe same file). Just an idea - feel free to ignore if it over complicates things!

Yeah your 100% correct @edwardsmarc - thanks for catching that!

**Comment by ricschuster** [comment]
@jeffreyhanson happy to create a new branch off of this one and merge back in when the review is complete.

**Comment by ricschuster** [comment]
@jeffreyhanson what's the package size you are getting when you check the package?

I'm at 49.2Mb which seems high

image

**Comment by jeffreyhanson** [comment]
Yeah that does seem high. My check shows (on Ubuntu):

```
* checking installed package size ... NOTE
  installed size is 28.9Mb
  sub-directories of 1Mb or more:
    doc    4.8Mb
    libs  20.8Mb
    R      1.3Mb
```

**Comment by ricschuster** [comment]
Just a quick note here:
This new way of printing `problem` is amazing Jeff!

image

**Comment by jeffreyhanson** [comment]
Thanks! Let me know if you have any suggestions for improving it

**Comment by edwardsmarc** [comment]
@jeffreyhanson, just curious: why did you need to create `print_problem()` in the vignettes instead of just calling `print()`?

I agree, the new `print` output looks awesome!

**Comment by jeffreyhanson** [comment]
Yeah, when just using `print()` in the vignettes, I found that the output didn't look correct in the html version of the vignette (I think this is due to issues with the cli package that is used for all the fancy printing). So, I created the `print_problem()` function to ensure that problems were printed correctly in the vignettes. It's not ideal though, and I wish using `print()` just worked - but I couldn't work out how to do this.

**Comment by jeffreyhanson** [comment]
Just making a note to remind myself this needs fixing:

In the file `assertions_misc.R` this line of code:

> "instructions in {.vignette prioritizr::gurobi_installation_guide}."

should be:

>  "instructions in {.vignette \"gurobi_installation_guide\"}."

**Comment by edwardsmarc** [comment]
Adding a note here about the new readMe example. I found a typo that I fixed from:
```
p3 <-
  p2 %>%
  add_locked_in_constraints(wa_locked_out)
```
to
```
p3 <-
  p2 %>%
  add_locked_out_constraints(wa_locked_out)
```
But this causes `solve(p3)` to fail because targets are impossible. There are 6 features that cannot be met to the 20% target. The code below pulls these out by comparing the available features (i.e. sum of non-locked-out PUs) to the 20% target. Removing those 6 features results in a successful `solve(p3)`:
```
wa_features <- get_wa_features()
wa_locked_out <- get_wa_locked_out()
wa_locked_out_inverse <- classify(wa_locked_out, matrix(c(0,1,1,0), ncol=2)) #switch 0's and 1's

# summed feature values of the non-locked out cells
available <- sapply(wa_features*wa_locked_out_inverse, function(x){
  sum(values(x), na.rm = TRUE)
  })

# 20% of total feature sums (i.e. target required to be met by solution)
twenty_p <- lapply(wa_features, function(x){
  sum(values(x), na.rm = TRUE) * 0.2
  })

tricky_birds <- which(!available > twenty_p)
names(wa_features[[tricky_birds]])

wa_features_fix <- wa_features[[-tricky_birds]]
p3 <-
  problem(wa_pu, features = wa_features_fix) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.01) %>%
  add_binary_decisions() %>%
  add_default_solver(gap = 0.1) %>%
  add_locked_in_constraints(wa_locked_in) %>%
  add_locked_out_constraints(wa_locked_out)
solve(p3)
```

Not sure what the best fix is here, removing these features from `get_wa_features()`?

**Comment by ricschuster** [comment]
@jeffreyhanson Gurobi recently introduced a core limit on academic licenses.
In the most recent license I am using the limit is 8.

On my system I have 24 cores. Running `devtools::test()` now leads to error messages like the below:
```
Error (test_add_asym_connectivity_penalties.R:208): minimum set objective (solve, single zone)
Error: Error 10009: Requested number of cores (24) is greater than allowed (8) cores
```

Might be useful to add a check in `add_gurobi_solver` to verify how many cores can be used.
What do you think?

**Comment by jeffreyhanson** [comment]
@edwardsmarc, thank you very much for catching this! Once you and @ricschuster have finished your reviews, I'll come back to the README and update it to fix this. I'm thinking that I might need to either update the dataset or the formulation (e.g. use different objective).

@ricschuster, thank you for raising this! All of the tests should use a single core (except perhaps some explicit multi-core tests in the solver tests that use 2 cores). So, I'm wondering if there's some problem with calling Gurobi in the testing, or calling Gurobi in R generally? Could you please verify if you can reproduce this error if you run this code in a fresh session (https://github.com/prioritizr/prioritizr/blob/v8/tests/testthat/test_decisions.R#L25-L37)?

**Comment by ricschuster** [comment]
Thanks for confirming @jeffreyhanson! When I had a look at the code I thought it odd that I got that error message, because I thought the tests should only be using 1 core. 
I get the same error when I run the code you linked in a fresh session.
Here my sessionInfo:

image

Anything else you would like me to test/look into?

**Comment by ricschuster** [comment]
What's strange is that I don't get this error message on Windows. 
(note R version is 4.1.1 on Windows)

image

**Comment by jeffreyhanson** [comment]
hmm, could you please try re-activating the license on your linux computer and see if that fixes it (see https://support.gurobi.com/hc/en-us/articles/360043663032-How-do-I-resolve-an-ERROR-10009-License-is-for-8-cores-machine-has-XX-)?

**Comment by jeffreyhanson** [comment]
@ricschuster, just had an idea for improving the print method. What do you think about moving the "solver" and "portfolio" sections out from underneath the "formulation" section, and putting them in a new section called "optimization" (or maybe you can think of a better term?)? This is because the solver isn't really part of the mathematical formulation.

**Comment by ricschuster** [comment]
> Hmm, could you please try re-activating the license on your linux computer and see if that fixes it (see https://support.gurobi.com/hc/en-us/articles/360043663032-How-do-I-resolve-an-ERROR-10009-License-is-for-8-cores-machine-has-XX-)? Although the link has a different error message, the error code seems to be the same as what you're seeing, so might be worth a shot.

Thanks @jeffreyhanson. I'm going to give this a try.

**Comment by edwardsmarc** [comment]
> > @ricschuster and @edwardsmarc, just had an idea for improving the print method. What do you think about moving the "solver" and "portfolio" information out from underneath the "formulation" section, and putting them in a new section called "optimization" (or maybe you can think of a better term?)? This is because the solver isn't really part of the mathematical formulation.
> 
> I like that idea! "optimization" sounds good to me as well.

I like that idea too! I think 'optimization' is a good term, it matches the language used in the vignettes.

**Comment by jeffreyhanson** [comment]
Ok excellent - thanks @ricschuster and @edwardsmarc! I'll work on updating the print method after you've finished looking at the current PR.

**Comment by ricschuster** [comment]
> > Hmm, could you please try re-activating the license on your linux computer and see if that fixes it (see https://support.gurobi.com/hc/en-us/articles/360043663032-How-do-I-resolve-an-ERROR-10009-License-is-for-8-cores-machine-has-XX-)? Although the link has a different error message, the error code seems to be the same as what you're seeing, so might be worth a shot.
> 
> Thanks @jeffreyhanson. I'm going to give this a try.

That fixed it. Thanks @jeffreyhanson!

**Comment by jeffreyhanson** [comment]
Awesome - no worries!

**Comment by edwardsmarc** [comment]
@jeffreyhanson - One suggestion I have for the documentation is an additional vignette on ILP. Targeted at the average user who understands the SCP concepts but not the mathematical underpinnings (i.e. me). ILP 101 if you will. 

For example, why/how is this better/different to simulated annealing? How does Gurobi know the optimality gap before calculating the optimal solution? How is the data passed from the problem() to the optimizer (i.e. what does the write_problem() output mean?).

I think a bit of background on this will help the intermediate to advanced user understand best practices and trade-off's between different approaches (e.g. those discussed in calibrating_trade-offs_tutorial.Rmd).

**Comment by jeffreyhanson** [comment]
@edwardsmarc, thanks for raising this suggestion! I don't really have the bandwidth to write a new vignette at the moment unfortunately.  Would you have time for this @ricschuster? If not, we could create an issue so we can circle back to this when i have more time. 

In response to your questions, (1) simulated annealing is a meta-heurisitc algorithm that you basically run for as long as you can be bothered and hope that the solution is good (it provides no guruantees on solution quality, unlike ILP), (2) Gurobi and other solvers use a different set of algorithms (called exact algorithms), and the specifics depend on the solver (e.g., branch-and-bound algorithms, branch-and-cut algorithms, see https://www.gurobi.com/resources/mixed-integer-programming-mip-a-primer-on-the-basics/), (3) the data is passed to the solver using other R packages (e.g., the gurobi R package for the Gurobi software), and the `write_problem()` is not used for this (its provided mainly so that people can output problems for other solvers if needed, don't know if anyone actually uses it). Does that help?

**Comment by edwardsmarc** [comment]
> @edwardsmarc, thanks for raising this suggestion! I don't really have the bandwidth to write a new vignette at the moment unfortunately. Would you have time for this @ricschuster? If not, we could create an issue so we can circle back to this when i have more time.
> 
> In response to your questions, (1) simulated annealing is a meta-heurisitc algorithm that you basically run for as long as you can be bothered and hope that the solution is good (it provides no guruantees on solution quality, unlike ILP), (2) Gurobi and other solvers use a different set of algorithms (called exact algorithms), and the specifics depend on the solver (e.g., branch-and-bound algorithms, branch-and-cut algorithms, see https://www.gurobi.com/resources/mixed-integer-programming-mip-a-primer-on-the-basics/), (3) the data is passed to the solver using other R packages (e.g., the gurobi R package for the Gurobi software), and the `write_problem()` is not used for this (its provided mainly so that people can output problems for other solvers if needed, don't know if anyone actually uses it though). Does that help?

Yes, this is helpful! The Gurobi website actually looks to have some useful resources. I'm happy to make this an issue for later unless @ricschuster wants to take it on.

**Comment by edwardsmarc** [comment]
FYI @ricschuster I removed you name and date from the gurobi_installation_guide.Rmd. So no need to do that in your branch.

**Comment by ricschuster** [comment]
> > @edwardsmarc, thanks for raising this suggestion! I don't really have the bandwidth to write a new vignette at the moment unfortunately. Would you have time for this @ricschuster? If not, we could create an issue so we can circle back to this when i have more time.
> > In response to your questions, (1) simulated annealing is a meta-heurisitc algorithm that you basically run for as long as you can be bothered and hope that the solution is good (it provides no guruantees on solution quality, unlike ILP), (2) Gurobi and other solvers use a different set of algorithms (called exact algorithms), and the specifics depend on the solver (e.g., branch-and-bound algorithms, branch-and-cut algorithms, see https://www.gurobi.com/resources/mixed-integer-programming-mip-a-primer-on-the-basics/), (3) the data is passed to the solver using other R packages (e.g., the gurobi R package for the Gurobi software), and the `write_problem()` is not used for this (its provided mainly so that people can output problems for other solvers if needed, don't know if anyone actually uses it though). Does that help?
> 
> Yes, this is helpful! The Gurobi website actually looks to have some useful resources. I'm happy to make this an issue for later unless @ricschuster wants to take it on.

I can't this on right now unfortunately. @edwardsmarc if you could create an issue for this that would be great!

**Comment by ricschuster** [comment]
> FYI @ricschuster I removed you name and date from the gurobi_installation_guide.Rmd. So no need to do that in your branch.

Thank you!

**Comment by ricschuster** [comment]
@jeffreyhanson my review is complete. Everything works well on my system and I haven't made any edits to the documentation as Marc is doing that. I have tested the package with a number of datasets (including a large one) and everything works well. The error message I have checked are informative and make sense.

Thanks very much for putting together this great update!

**Comment by edwardsmarc** [comment]
Hey @jeffreyhanson. The calibrating trade-offs vignette has a bunch of warnings in the first chunk of the **Calculating performance metrics** section. Specifically the call to `eval_boundary_summary()` which is triggering a warning on the following test in the function:
```
verify(
    all(
      Matrix::diag(data) >=
      (Matrix::rowSums(data) - Matrix::diag(data))
    ),
    msg = c(
      "{.arg data} has unexpected values.",
      "x" = paste(
        "If {.arg data} is from an older version of",
        "{.pkg prioritizr}, then use",
        "{.fn boundary_matrix} to recreate it."
      ),
      "i" = paste(
        "{.arg x} might have spatially overlapping planning units."
      ),
      "i" = paste(
        "If {.arg solution} has selected multiple spatially",
        "overlapping planning units, then results will be incorrect."
      )
    )
  )
```

I think this is testing that the total shared boundary does not exceed the total boundary of each planning unit? A bunch of the planning units in **tas_pu** seem to fail this check.

**Comment by jeffreyhanson** [comment]
Thanks so much for catching this @edwardsmarc! I definietly think the example datasets should not trigger any warnings. I'll take a proper look into this once you've completed the rest of your review.

**Comment by edwardsmarc** [comment]
@jeffreyhanson I'm trying to push my branch but getting a permission error. Do I need to be added as a contributor?

**Comment by jeffreyhanson** [comment]
@edwardsmarc, yeah that's probably it. I've just invited you to the prioritizr-dev team, once you accept, you should be able to push the updates. Let me know if that doesn't work?

**Comment by edwardsmarc** [comment]
@jeffreyhanson I've finished reviewing the website documentation. Most of my edits are fixing typos, I'll explain a few other changes here:
- In `add_manual_targets()`, the **zone** column in the table to the **targets** argument can take a list of vectors of zone names (in the use case where targets are specific to each feature regardless of zone). This is not clear in `?add_manual_targets` where it only mentions taking a character of names. **I haven't edited this text, just flagging it here**.
- I made a change to the Details section of `add_absolute_targets()` so it makes sense when inherited into the `add_manual_targets()` Details section.
- In the connectivity tutorial, I changed the `plot()` legend to use `type = “classes”` to make legends fit when plotting two maps side-by-side.
- In the solver benchmarks vignette, I added a `suppressWarnings()` to the helper function to prevent warnings when solvers don’t have any results to plot in the graph.
- Fixed `salt_con_binary` in the connectivity vignette as discussed at the top of this thread.

So far I've only reviewed the vignettes. The edits I made to the function documentation were just opportunistic edits while reading up on specific functions. Would you like me to review all function documentation on the **References** page of the website for this PR? I expect it'll take me another week.

I also generated a bunch of errors and they were all formatted correctly.

**Comment by jeffreyhanson** [comment]
Thank you very much for all that @edwardsmarc! Thanks for catching that omission in `add_manual_targets()`  - that should definitely be addressed. To avoid creating meerge conflict issues, I'll address that in a follow up PR after you're has been merged. Yeah, if you don't mind, it would be absolutely amazing if you could go through all the documentation on the references page too?

**Comment by edwardsmarc** [comment]
> Thank you very much for all that @edwardsmarc! Thanks for catching that omission in `add_manual_targets()` - that should definitely be addressed. To avoid creating meerge conflict issues, I'll address that in a follow up PR after you're has been merged. Yeah, if you don't mind, it would be absolutely amazing if you could go through all the documentation on the references page too?

Thanks @jeffreyhanson, I'll work on the function documentation this week and let you know when it's done.

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much @edwardsmarc!!

**Comment by edwardsmarc** [comment]
@jeffreyhanson I've finished my edits to the function documentation. Here are a few comments:
- `solve.R` – removed a duplicate example
- In `adjacency_matrix.R`
  - Changed polygon subsetting to make cleaner plots (same change applied to other matrix function examples)
  - I’m not sure if the `sf line` example here is meant to produce any output. It doesn’t because the lines don’t intersect so the output is an empty matrix
- Update to previous issue I mentioned above: `eval_boundary_summary()` seems to throw the warning every time a polygon solution is evaluated
- In gurobi and cbc solver pages, a short explanation of why you might want to use a `start_solution` would be helpful
- In `rij_matrix` there's an example using zones, but the zones are just treated as planning units so the result is the same as using a pu raster dataset. Consider removing?

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much @edwardsmarc!! IIRC all your changes are in a different branch to this one? If so, could you please make sure all the changes are pushed to github and open a PR to merge the changes into this branch? This way I can go through the PR to see all the changes you've made. How does that sound? If you're not sure how to open a PR, I can do that- just let me know the name of the branch?

**Comment by edwardsmarc** [comment]
Thanks @jeffreyhanson, I just made the PR.

**Comment by jeffreyhanson** [comment]
Excellent - thanks @edwardsmarc!

**Comment by jeffreyhanson** [comment]
I've just gone through your PR, made a couple of tweaks, and merged it into the V8 branch. Massive thank you @edwardsmarc! I really appreciate you going over the documentation so carefully! It's so much better now!

**Comment by ricschuster** [comment]
Hi @jeffreyhanson @edwardsmarc incorporated my proposed edits into his PR, so we are all good from my end.

**Comment by jeffreyhanson** [comment]
Ah - awesome - thanks for the quick response!

**Comment by ricschuster** [comment]
@edwardsmarc I did only make tiny edits that I realized you had already incorporated in your branch when we last talked about your review. All good.

**Comment by jeffreyhanson** [comment]
I've updated the datsaset in prioritizrdata and the README. If you have a moment, @edwardsmarc or @ricschuster, could you please take a look at README.Rmd and see what you think?

**Comment by edwardsmarc** [comment]
@jeffreyhanson I just pushed a few edits to the readMe. Couple of typos and I also set the planning units costs to zero for the solution using locked in constraints. Feel free to remove this if you think it's too involved. It just means that representation results make a bit more sense. i.e. they increase from PAs only, to problem 1, to problem 2. Without doing this the representation of the locked_in solution (problem 2) is lower than the base problem (problem 1).

**Comment by jeffreyhanson** [comment]
Thank you very much @edwardsmarc! I might tweak some of your suggestions to the code, if that's ok? As a general rule, I don't recommend that beginners set costs to zero, because that can cause somewhat unexpected results unless taken care of properly (e.g., if the existing protected areas were set to zero costs but not locked in, you might find that only some of the existing protected areas appear in the solution). Also I'd like the README to emphasize that problems can be customized by adding increased complexity to a base problem. How does that sound?

**Comment by edwardsmarc** [comment]
> Thank you very much @edwardsmarc! I might tweak some of your suggestions to the code, if that's ok? As a general rule, I don't recommend that beginners set costs to zero, because that can cause somewhat unexpected results unless taken care of properly (e.g., if the existing protected areas were set to zero costs but not locked in, you might find that only some of the existing protected areas appear in the solution). Also I'd like the README to emphasize that problems can be customized by adding increased complexity to a base problem. How does that sound?

No problem! I wasn't if it was appropriate so figured I'd leave it and let you decide.

**Comment by jeffreyhanson** [comment]
@ricschuster and @edwardsmarc, I've added some tweaks to the custom error messages so that when users input invalid arguments (e.g. like mispelling the name of an argument, or input expressions that throw an error), the user should see a helpful errror. I've included some examples below. I think these look ok  - what do you think? Also, can you think of any other potential errors worth testing to verify that the error message parsing works as intended?

```
# load data and package
devtools::load_all()
sim_pu_raster <- get_sim_pu_raster()
sim_features <- get_sim_features()

# create problems, but specify an argument that doesn't exist
p1 <-
  problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(object_not_exist) %>%
  add_binary_decisions()

#> Error in `add_relative_targets()`:
#> ℹ In argument to `targets`.
#> Caused by error:
#> ! object 'object_not_exist' not found
#> Run `rlang::last_trace()` to see where the error occurred.

p2 <-
  problem(object_not_exist, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets() %>%
  add_binary_decisions()

#> Error in `problem()`:
#> ℹ In argument to `x`.
#> Caused by error:
#> ! object 'object_not_exist' not found
#> Run `rlang::last_trace()` to see where the error occurred.

# create some problems, but specify an argument that is an invalid expression
p3 <- 
  problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1 + "a") %>%
  add_binary_decisions() 

#> Error in `add_relative_targets()`:
#> ℹ In argument to `targets`.
#> Caused by `0.1 + "a"`:
#> ! non-numeric argument to binary operator
#> Run `rlang::last_trace()` to see where the error occurred.

# let's make sure that it works with pipe expressions
p4 <- 
  problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(
    5 %>%
    runif() %>%
    `+`("a")
  ) %>%
  add_binary_decisions()

#> Error in `add_relative_targets()`:
#> ℹ In argument to `targets`.
#> Caused by `. + "a"`:
#> ! non-numeric argument to binary operator
#> Run `rlang::last_trace()` to see where the error occurred.

# let's make sure that it works with multiple function calls
p5 <- 
  problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(
    data.frame(c("a" + 1))
  ) %>%
  add_binary_decisions()

#> Error in `add_relative_targets()`:
#> ℹ In argument to `targets`.
#> Caused by `"a" + 1`:
#> ! non-numeric argument to binary operator
#> Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson! They look good to me.
I can't think of anything else to test related to error messages at this point.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson! They look good to me.
I can't think of anything else to test related to error messages at this point.

**Comment by edwardsmarc** [comment]
Looks good to me too @jeffreyhanson.

Here's another error to test, missing budget:

```
p6 <-
  problem(sim_pu_raster, sim_features) %>%
  add_min_largest_shortfall_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()
```

**Comment by jeffreyhanson** [comment]
Awesome - thank you @ricschuster and @edwardsmarc!

**Comment by jeffreyhanson** [comment]
Ok - I think the PR is almost ready for merging to main. @edwardsmarc and @ricschuster, can you think of anything else that needs doing before merging? Also, what's the plan the for the CRAN release? Should we submit to CRAN shortly after the merge (e.g., within the next couple of days after merge), or sit wait for a bit (e.g., a month or more?) to see if any issues crop up?

**Comment by edwardsmarc** [comment]
@jeffreyhanson, this is great! I can't think of anything else to do before merging. I'll defer to @ricschuster on the CRAN question. I don't have any experience with that.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson!
I'd say, lets push to CRAN shortly after the merge so we get a wider user group to test v8.
What do you think @jeffreyhanson?

**Comment by ricschuster** [comment]
Checks passed. Submitting to CRAN now.
Fingers crossed!

**Comment by jeffreyhanson** [comment]
Woo - thank you!

**Pull request merged**
