### PR TITLE
Update vignettes

### PR DESCRIPTION
**Pull request by jeffreyhanson**
I thought that it might be worth going over the Tamsania vignette and updating it, given our upcomming workshop. 

@ricschuster, when you get a chance, could you take a look and let me know what you think? In particular, I'm hoping this vignette will now serve as a more quick introduction to prioritizr, and show off some of the newer features that weren't available when it was first written (e.g. irreplaceability, feature representation).

Also, I'm also working on a parameter calibration vignette so we can go through the process of performing a boundary length calibration exercise - I'll push a commit with that when it's ready for feedback.

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Also, please feel free to push any commits that add any edits/tweaks/ideas to the vignette.

**Comment by jeffreyhanson** [comment]
Thanks! 

I'm sorry - I'm just realized I forgot to include the correct Rmarkdown file (`vignettes/tasmania.Rmd`) in the commit - so I think you might have looked at the previous version of the vignette. I'll make some more tweaks and push another version for you to look at.

Regarding the selection frequency stuff: Since we have several functions for exploring planning unit importance, I don't really think selection frequencies are best practice anymore. So, in the updated version I removed this entirey. After thinking more about this, I'll add a small bit to the vignette on generating portfiols -- in the context of generating multiple solutions to present to decision makers or stakeholders. How does that sound?

**Comment by ricschuster** [comment]
Ah, now things make more sense. I was wondering why there was so much selection frequency text in the vignette. 

All sounds good. Just let me know when you want me to have another look.

**Comment by jeffreyhanson** [comment]
@ricschuster, I've just pushed an update - could you please take a look at the Tasmania vignette again? It should look very different from before - please let me know if I messed up the commits again.

**Comment by ricschuster** [comment]
Yeah, that looks very different now. I like the updated structure and description a lot.
I went through the vignette and have nothing to add at this point.
Thanks!

**Comment by jeffreyhanson** [comment]
Awesome - thank you!

**Comment by jeffreyhanson** [comment]
@ricschuster, I was wondering if it might be worth updating a couple of the other vignettes too. If you have a moment, here's some random thoughts I'd appreciate your input on.

1. The main prioritizr vignette provides detailed overview of pretty much every function in the package. This is (hopefully?) helpful for interested readers, but might not be very useful for readers interested in a quick overview - so having it listed under "Getting started" on the website might be a bit overwhelming? What do you think? Would it be worth making the updated Tasmania vignette the new default prioritizr vignette, and renaming the current prioritizr vignette to something else (e.g. like package overview?)

2. What's the main message/take-away from the Salt Island Spring vignette? It show cases a few different solvers and methods or adding connectivity - but is this still useful? E.g., the benchmark vignette provides a better understanding of the different solvers. Maybe this should be updated to focus specifically on different methods for connectivity?

**Comment by jeffreyhanson** [comment]
@ricschuster, when you have a chance, could you please take a look at the new multi-criteria decision analysis vignette (i.e. `vignettes/mcda.Rmd` and `inst/doc/mcda.html`)? I've framed this as a "this is how to explore trade-offs tutorial, and we will cover boundary length calibration as an example" - what do you think? I thought this might be more useful than simply a "this is how to do boundary length calibration tutorial". Also, please let me know if any of the concepts or terminology is unclear or inconsistent?

**Comment by ricschuster** [comment]
> @ricschuster, when you have a chance, could you please take a look at the new multi-criteria decision analysis vignette (i.e. `vignettes/mcda.Rmd` and `inst/doc/mcda.html`)? I've framed this as a "this is how to explore trade-offs tutorial, and we will cover boundary length calibration as an example" - what do you think? I thought this might be more useful than simply a "this is how to do boundary length calibration tutorial". Also, please let me know if any of the concepts or terminology is unclear or inconsistent?

This is an awesome vignette!
I'm still working my way through the vignette and am making a few tiny changes, but I will record some comments here.

Line 196 (`prelim_blended_results`): I think the structure of generating this variable will be too complicated for many R users. What do you think about splitting this up into easier to digest pieces?

Line 221 (`r prelim_penalty[8]`): From looking at the maps from the previous chunk I would have thought the last `prelim_penalty` (i.e. [9]) would be chosen as the upper limit. Am I wrong in this assessment?

Line 325 (setting costs to 0): What do you think about setting costs to 0.01 or some small number instead of 0. I wonder if setting costs to 0 here would prompt people to set costs to 0 in other cases as well, which will lead to unintended consequences? Maybe I'm too cautious here, but I wanted to see what you think about this.

Line 327 code chunk: Given that the previous code chunk has used `gap = 0`, I am wondering if it would be worth it to include the gap parameter here as well? I know this chunk uses the default gap value, but I am wondering whether it would help users to understand what's going on?

**Comment by ricschuster** [comment]
> @ricschuster, I was wondering if it might be worth updating a couple of the other vignettes too. If you have a moment, here's some random thoughts I'd appreciate your input on.
> 
>     1. The main prioritizr vignette provides detailed overview of pretty much every function in the package. This is (hopefully?) helpful for interested readers, but might not be very useful for readers interested in a quick overview - so having it listed under "Getting started" on the website might be a bit overwhelming? What do you think? Would it be worth making the updated Tasmania vignette the new default prioritizr vignette, and renaming the current prioritizr vignette to something else (e.g. like package overview?)
> 
>     2. What's the main message/take-away from the Salt Island Spring vignette? It show cases a few different solvers and methods or adding connectivity - but is this still useful? E.g., the benchmark vignette provides a better understanding of the different solvers. Maybe this should be updated to focus specifically on different methods for connectivity?

1. I like the idea of making the updated Tasmania vignette the new default prioritizr vignette and renaming the current one into package overview. I do like the current 'Getting started' one a lot and find it super useful.

2. To me the Salt Spring Island vignette has always been the place where I sent people to learn how to use prioritizr with raster data. Its nice that the vignette is relatively short and not too overwhelming. Removing the range of solver component and focusing more on connectivity sounds like a good idea. The connectivity component tends to take a while though if people don't have Gurobi installed, so maybe having some fairly basic functionality and relatively fast components would be more useful to users?

**Comment by jeffreyhanson** [comment]
Brilliant - thank you very much @ricschuster! Once you've finished going through the vignette, I'll update it to fix those issues. Could you please let me know when you've finished pushing any edits? 

> 
> Line 196 (`prelim_blended_results`): I think the structure of generating this variable will be too complicated for many R users. What do you think about splitting this up into easier to digest pieces?

Great idea!
 
> Line 221 (`r prelim_penalty[8]`): From looking at the maps from the previous chunk I would have thought the last `prelim_penalty` (i.e. [9]) would be chosen as the upper limit. Am I wrong in this assessment?

No, you're absolutely correct. I should increase the upper limit parameter so that `[8]` is actually correct.

> Line 325 (setting costs to 0): What do you think about setting costs to 0.01 or some small number instead of 0. I wonder if setting costs to 0 here would prompt people to set costs to 0 in other cases as well, which will lead to unintended consequences? Maybe I'm too cautious here, but I wanted to see what you think about this.

The costs need to be 0 here so that the optimization focusses purely on boundary length. I could add in a note explaining why zero costs are not normally recommended, and explain why, and then explain why we want zero costs here?

> Line 327 code chunk: Given that the previous code chunk has used `gap = 0`, I am wondering if it would be worth it to include the gap parameter here as well? I know this chunk uses the default gap value, but I am wondering whether it would help users to understand what's going on?

Yeah, good idea - I can add that.

**Comment by jeffreyhanson** [comment]
> 1. I like the idea of making the updated Tasmania vignette the new default prioritizr vignette and renaming the current one into package overview. I do like the current 'Getting started' one a lot and find it super useful.

Ok great - let's do that. What is a good name for renaming the current prioritizr vigentte? I always find it challenging to name things like this. Package overview? Package description? Package guide? Package handbook?

> 2. To me the Salt Spring Island vignette has always been the place where I sent people to learn how to use prioritizr with raster data. Its nice that the vignette is relatively short and not too overwhelming. Removing the range of solver component and focusing more on connectivity sounds like a good idea. The connectivity component tends to take a while though if people don't have Gurobi installed, so maybe having some fairly basic functionality and relatively fast components would be more useful to users?

Ah yes - that's right, I forgot raster data was the original idea behind it. Yeah, good point regarding run times. I'll have a think about some ideas for this vignette and follow up with you.

**Comment by ricschuster** [comment]
> Brilliant - thank you very much @ricschuster! Once you've finished going through the vignette, I'll update it to fix those issues. Could you please let me know when you've finished pushing any edits?

Thanks Jeff! I'm done with my edits for now.

**Comment by ricschuster** [comment]
> Ok great - let's do that. What is a good name for renaming the current prioritizr vigentte? I always find it challenging to name things like this. Package overview? Package description? Package guide? Package handbook? Any ideas?

I like Package overview.

> Ah yes - that's right, I forgot raster data was the original idea behind it. Yeah, good point regarding run times. I'll have a think about some ideas for this vignette and follow up with you.

Sounds good, thanks.

**Comment by jeffreyhanson** [comment]
@ricschuster, I've just pushed some udpates to the vignettes. When you get a chance, could you please take a look? 

Specifically, (i) I've made some tweaks to the MCDA vignette, (ii) renamed the Tasmania vignette to the main vignette, and (ii) renamed the old main vignette to a Package overview vignette. I've renamed + edited the MCDA vignette to "Calibrating trade-offs" - what do you think? I was worried calling that people looking for info on boundary calibration stuff might miss if it was "Multi-criteria decision analysis" called? I've also added a second quantitative method to the vignette too (i.e. the Cohon method).

**Comment by jeffreyhanson** [comment]
Just rebuilt the site,I won't be making any further changes so please feel free to commit/push any edits.

**Comment by ricschuster** [comment]
I really like the changes you have made.
The `prioritizr.Rmd` vignette is a great introduction!

What do you think about a short description of each of the vignettes either on the main landing page or in `prioritizr.Rmd`? I think it could be good to make users aware of the vignettes right away. This is mainly aimed at people visiting the website as they might not be familiar with vignettes yet.

Another idea I had was to either move or replicate section `package_overview.html#package-overview-1` on the main landing page (i.e. `README.Rmd`) or `prioritizr.Rmd`. If I look at the website, that's usually the first place to go to to jump to the appropriate section.

re: Cohon method. Very interesting addition. Do you have a sense whether anyone has compared the three methods described in a more or less systematic way across a range of projects? I would be curious to learn whether the general pattern we see with Tasmania (BL of visual < TOPSIS < Cohon) would be observed in other projects too or whether that's Tasmania specific.

In `calibrating_trade-offs.Rmd`, I see this (line 507+):
```
# generate ideal prioritization based on spatial fragmentation criteria
## note that any non-zero penalty value would here,
## so we just use a penalty  of 1 because
```
Those sentences are missing words.

Other than that, I think everything looks great. I have to say that I didn't go over the vignettes in detail though.

**Comment by jeffreyhanson** [comment]
Awesome- thanks! Yeah, I really like those ideas - I'll incorperate them and then get working on the connectivity tutorial.

**Comment by ricschuster** [comment]
Thanks very much Jeff!
The package documentation is truly awesome and (I think) really helps make `prioritizr` more accessible to new and returning users alike.

**Comment by jeffreyhanson** [comment]
@ricschuster, I've just pushed an update with the Salt Sprint Island vignette reworked into a connectivity tutorial - could you please take a look? I've also added a learning resources section to the REAMDE with links to all the the vignetes. I won't be making any further updates till I hear back from you, so please feel free to push/commit and edits/changes.

**Comment by jeffreyhanson** [comment]
Sorry - I just realized some links in the REAMDE didn't work, so I've pushed that now. I promise I won't make any further changes now

**Comment by ricschuster** [comment]
Awesome! The Salt Spring Island/connectivity vignette looks great!

I was thinking about a location for the 'Learning resources' section that people will see right away. What do you think about moving it to the top of the 'Getting Started' section/prioritizr.Rmd vignette?

**Comment by jeffreyhanson** [comment]
Yeah, that's a good point. I agree the learning resources section is a bit hidden because the users have to scroll all the way down on the README. What do you think about including adding a summay of the other vignettes to the conclusion section of the getting started tutorial? I feel like the point of a getting started tutorial (or quick start guide) is to quickly show users the main functionality - so having learning resources at the top might be distracting?

**Comment by ricschuster** [comment]
> What do you think about including adding a summay of the other vignettes to the conclusion section of the getting started tutorial?
I think that's a good idea. Lets do that.

**Comment by jeffreyhanson** [comment]
Ok excellent - I'll do that, bump the version, and then rebuild the site. Is there anything we need to do before merging the PR?

**Comment by ricschuster** [comment]
Thanks Jeff!
Nothing left from my end.

**Pull request merged**
