### PR TITLE
Add linear penalties and improve documentation

### PR DESCRIPTION
**Pull request by jeffreyhanson**
Thanks for agreeing to review this PR Richard. It adds the following changes:
- New `add_linear_penalties` to add penalties that penalize planning units according to a linear metric.
- Update `connectivity_matrix` documentation to provide an example of how to generate connectivity matrices that account for functional connectivity.
- Add more information to the documentation for the `solve` function.
- Add links to the documentation for the  `solve` function to the Salt Spring Island and Tasmania vignettes.

Let me know if you have any questions? Once you've reviewed it, I'll rebuild the package website and merge it.

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Note that the automated checks won't pass due to new R-devel check. I'm hoping the new R-devel check will get removed soon.

**Comment by ricschuster** [comment]
Thanks very much for the updated documentation for the various functions mentioned in the pull request! All looks great on that front.

The files related to `add_linear_penalties` are all good as well and I didn't notice any errors or problems there in terms of the code.

I do however have a philosophical and functional question about the function as well as a question for clarification on the documentation of the function.

1) functionality: 
having a look through the code in `add_linear_penalties.R` and especially `rcpp_apply_linear_penalties.cpp` it looks to me like the result of applying the `add_linear_penalties` function is a modification of the objective/cost values. Am I reading the code wrong or is this actually the case? 
If this is the case, what's the rational for adding cost values in the `problem` function, when we then modify this cost via the `add_linear_penalties` function? 
To me that seems a bit strange, but would be great to understand the reasoning behind this approach. Maybe I just haven't thought about this enough to understand why this function makes sense to add.

2) documentation: 
This is related to the functionality question and maybe just me not understanding the equation you use in the function documentation. Starting line 79 in `add_linear_penalties.R` you describe the penalty first in words and then mathematically. If my reading of the code is correct and the function does indeed what I described in the previous paragraph, I don't quite understand how this part of the documentation relates back to the penalty just adding to the objective function/values. I wonder if it would make sense to mention this explicitly here?

**Comment by jeffreyhanson** [comment]
Hi,

With regards to your question,

1. Yeah, this penalty function allows the user to modify the objective values so that selecting planning units are penalised more heavily in the solution. For example, if you want to avoid solutions with high anthropogenic pressure scores, then one approach would be to add penalties to the problem based on anthropogenic scores. Crucially, the penalties do not over-write the values the in the objective function, and are instead added to it (i.e. the code uses the `+=` operator and not the `=` operator). In the minimum set formulation, this would be equivalent to creating a composite cost layer based on multiple variables and a penalty/weighting score (e.g. `cost = $$ * 5 * anthropogenic pressure`) and the advantage of the `add_linear_penalties` function here is that users don't have to pre-compute these values. For budget-limited problems, the objective is not cost and so the `add_limited_penalties` function allows the users to set a budget using one variable (e.g. $$) and then penalize the main objective (e.g. number of features adequately represented, phylogenetic diversity) according to the another variable (e.g. anthropogenic pressure). In general, I think the linear penalties will be more useful for budget-limited formulations. Does that make sense?

2. These equations describe the values that are added to the objective function (e.g. similar to the documentation for the boundary penalties; https://prioritizr.net/reference/add_boundary_penalties.html)

**Comment by ricschuster** [comment]
Thanks for confirming the `+=` part, that's what I thought. For the min_set objective function, I think it would be important to make sure to document this well, so users don't get confused. Given that `add_linear_penalties` does change the objective values, I'm still not sure how useful it will be in practice for min_set, but that's just me.

I do like the use for budget limited formulations though. The problem formulation is getting more complicated though and I wonder how likely users would be to use this penalty in a way it wasn't meant to be used.

More broadly, do you think it would be useful to add a vignette/help page to the prioritizr website that would show the full objective function formulation for different objective function and constraint/penalty formulations? Would be even cooler if there would be a way to make this interactive (i.e. user picks a combination of things and the mathematical formulation is generated), but I don't know if that's easy to do.

**Comment by ricschuster** [comment]
Lets merge the pull request back in and I will open for the vignette with formulas.

**Comment by jeffreyhanson** [comment]
I'm sorry, I forgot to respond to your post. Ok - glad to hear that you think the linear penalties are useful and not too confusing. Yeah, I agree that they could be misused if not applied properly. 

Thanks for approving and merging the PR. I'll comment on the formula stuff in the new issue.

**Pull request merged**
