### PR TITLE
Add cplex solver

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR adds a new `add_cplex_solver` function to generate solutions using IBM CPLEX (via the Rcplex package). @ricschuster, could you take a look and let me know what you think? The relevant changes are in:
* R/solvers.R
* R/add_cplex_solver.R
* vignettes/prioritizr.Rmd
* tests/testthat/solvers.R

### CODE REVIEW

**Comment by ricschuster** [comment]
Awesome!
Thanks very much for adding the new solver.
I've only had a look at the code so far, as I'm currently running on Windows and haven't gotten `Rcplex` to install properly yet. Will keep working on that and try out this branch once that's solved.

**Comment by jeffreyhanson** [comment]
Ok excellent! It would also be good to verify if you can successfully install this dev version of prioritizr without CPLEX installed. Although Rcplex is listed under Suggests, it will fail to install if CPLEX isn't found on the system. If this failure throws an error, this could make it difficult for users to install prioritizr without CPLEX installed? Can you see if this happens?

**Comment by ricschuster** [comment]
I have CPLEX installed but not `Rcplex`. 
Using `remotes::install_github("prioritizr/prioritizr", ref = "cplex")`
was successful and did install the cplex branch, which is encouraging.

I will continue trying to get `Rcplex` installed to properly test this on Windows.

**Comment by jeffreyhanson** [comment]
Ok great! On my computer, I had to create a `CPLEX_BIN` system variable to specify where CPLEX was installed. Specifically, I added this `export CPLEX_BIN="/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux/cplex"` to my `~/.bashrc` file. In case this helps, here's the install instructions for Rcplex: https://cran.r-project.org/web/packages/Rcplex/INSTALL. For Windows, it says:

> ***WINDOWS***
> 
> Installation on Windows systems is done by using the provided
> Makevars.win file in the src directory. It contains the following
> lines:
> 
> ifeq "$(WIN)" "64"
> PKG_LIBS = -L"${CPLEX_DIR}/bin/x64_win64" -lcplex1263 -lm
> PKG_CPPFLAGS = -D_LP64 -I"${CPLEX_DIR}/include"
> else
> PKG_LIBS = -L"${CPLEX_DIR}/bin/x86_win32" -lcplex1263 -lm
> PKG_CPPFLAGS = -I"${CPLEX_DIR}/include"
> endif
> 
> where ${CPLEX_DIR} references to the cplex installation directory and
> can be set in the Makevars.site configuration file for the given
> architecture in your R installation. If you are using a different
> version of CPLEX than 12.6.3 then please edit your Makevars.win file
> accordingly.
> 
> We have successfully tested this procedure with the IBM ILOG CPLEX
> Community Edition 12.6.3 on 64-bit Windows 7. 32 bit is currently not
> supported. Please install the package using "R CMD INSTALL
> --no-multiarch Rcplex_0.3-3.tar.gz" on 64 bit systems.
>

**Comment by ricschuster** [comment]
Thanks Jeff!

I've tried the `Rcplex` install instructions as well as the `cplexAPI` instructions (https://cran.r-project.org/web/packages/cplexAPI/INSTALL), but haven't gotten it to work yet.
Just need to play around some more with this I guess.

Also looks like as if `Rcplex` wasn't actively developed anymore, but `cplexAPI` still is.

**Comment by jeffreyhanson** [comment]
Yeah, it looks like `cplexAPI` also offers more functionality too (e.g. specifying number of threads and functionality to generate portfolios with specific criteria similar to Gurobi). I went with `Rcplex` because it seemed a lot easier to use. My impression is that Gurobi is supposed to be faster than CPLEX, so I tried cobbling together a minimum working version for CPLEX in this PR. If it looks like CPLEX is comparable (or faster) than Gurobi after playing with some data, maybe it's worth switching over to `cplexAPI` to provide more enhanced functionality? What do you think?

**Comment by jeffreyhanson** [comment]
Also, if cplexAPI is much easier to install on Windows, maybe that alone is reason for switching over?

**Comment by ricschuster** [comment]
The comparable, or even faster, speed sounds very encouraging.
Given this, I think it might be worth considering going with `cplexAPI` instead of `Rcplex`, as it looks like `cplexAPI` does have a lot more flexibility and is still maintained/developed.

Will give installing `cplexAPI` a go as well. All in all this is very encouraging and would be really neat to have a fast Gurobi alternative available.

**Comment by jeffreyhanson** [comment]
Sorry, to clarify, I don't know how well CPLEX compares to Gurobi. My impression from reading previous benchmarks online (applied to operations research problems) is that Gurobi is generally faster than CPLEX -- but it could be possible that CPLEX performs as fast (or faster) than Gurob for conservation planning-type problems.

**Comment by ricschuster** [comment]
Thanks for the clarification. I had the same impression as you from reading benchmarks reports online as well. Would be really neat if CPLEX would show comparable performance for conservation planning-type problems. This is part of the reason why I really want to get the package to work here. I guess I could just boot into Linux to do some benchmarking as well.

**Comment by ricschuster** [comment]
Jeff, I just saw you are using `CPLEX_Studio128`. I seem to have downloaded the community version `CPLEX_Studio_Community1210`. Not sure if that will make a difference for me, but I should probably look into getting the full version. Anything special you had to do for that?

**Comment by jeffreyhanson** [comment]
Hmm, the community version might have limits on it that prevent solving large problems - I'm not sure. Yeah, I was able to get an academic license somehow. I can't exactly remember how I did this - I installed CPLEX years ago but never got around to playing with it. Maybe there's an option on the website to register an academic account? I'll have a quick look.

**Comment by jeffreyhanson** [comment]
Maybe try creating an account here and see if it works? https://www.ibm.com/academic/technology/data-science

**Comment by ricschuster** [comment]
Thanks Jeff!

**Comment by ricschuster** [comment]
When trying to install `Rcplex` on Mint, I get an error (`cplexAPI` works fine):

```
configure: error: Could not link CPLEX library using -L/opt/ibm/ILOG/CPLEX_Studio1210/cplex/lib/x86-64_linux/static_pic -l$(CPLEXLIB) -lm -lpthread -ldl
ERROR: configuration failed for package ‘Rcplex’
* removing ‘/home/richard/R/x86_64-pc-linux-gnu-library/4.0/Rcplex’
```

Did you get that too and if so how did you fix it?
(I did export the `CPLEX_BIN` variable)

**Comment by jeffreyhanson** [comment]
I don't know sorry - it worked for me once I set the CPLEX_BIN variable. Does the `L/opt/ibm/ILOG/CPLEX_Studio1210/cplex/lib/x86-64_linux/static_pic` folder exist on your computer? Maybe you could specify the `--with-cplex-dir` option? For reference, here's the Linux instructions:

> ***LINUX INSTALLATION***
> 
> For Linux, pointers on where to find this information can be found in
> <cplex_dir>/readme.html where <cplex_dir> is your cplex installation
> directory.  The easiest way is to look at variables CFLAGS and
> CLNFLAGS in <cplex_path>/examples/<system>/<libformat>/Makefile. For
> example, that Makefile might have
> 
> CFLAGS = -fPIC -I${CPLEX_INCLUDE_PATH}
> CLNFLAGS = -L${CPLEX_LIB_PATH}/static_pic -lcplex -lm -lpthread
> 
> Set/replace the ${CPLEX_INCLUDE_PATH} and ${CPLEX_LIB_PATH} with the
> corresponding paths to the 'include' and 'lib' directories of your
> CPLEX installation on your system.
> 
> Given this information, there are several ways of installing the
> Rcplex package:
> 
>   1) Set the PKG_CFLAGS, PKG_CPPFLAGS and PKG_LIBS used by R's
>     installation procedure directly:
> 
>     R CMD INSTALL --configure-args="PKG_CFLAGS=-fPIC \
>     PKG_CPPFLAGS=-I${CPLEX_INCLUDE_PATH} \
>     PKG_LIBS='-L${CPLEX_INCLUDE_PATH}/static_pic \
>     -lcplex -lm -lpthread'" Rcplex_0.3-0.tar.gz
> 
>     If either PKG_CPPFLAGS or PKG_LIBS is given then both must be
>     given, otherwise configure with stop with an error
> 
>   2) Use --with-cplex-<ARG> to pass this information along:
> 
>     R CMD INSTALL \
>     --configure-args="--with-cplex-include=${CPLEX_INCLUDE_PATH} \
>     --with-cplex-cflags=-fPIC \
>     --with-cplex-lib='-L${CPLEX_LIB_PATH}/static_pic \
>     -lcplex -lm -lpthread'" Rcplex_0.3-0.tar.gz
> 
>     If either --with-cplex-include or --with-cplex-lib is given, then
>     both must be given, otherwise configure will stop with an error
> 
>   3) Give the location of your CPLEX installation:
> 
>     R CMD INSTALL --configure-args="--with-cplex-dir=${CPLEX_DIR}"\
>     Rcplex_0.3-0.tar.gz 
> 
>     This method requires that ${CPLEX_DIR} looks exactly as installed
>     by CPLEX. It will take the first system type and library format it
>     finds and fills the information above from the Makefile it should
>     find in <cplex_path>/examples/<system>/<libformat>/. Info is
>     pulled from the Makefile using awk, so it must be present for
>     installation to work.
> 
>   4) Don't give any information at all:
> 
>     R CMD INSTALL Rcplex_0.3-0.tar.gz
> 
>     This method looks for the CPLEX interactive optimizer, or,
>     alternatively, gets this information from the CPLEX_BIN
>     environment variable. Then it uses the directory two levels above
>     as the CPLEX installation directory. Afterwards, it does the same
>     thing as #3 above.

**Comment by ricschuster** [comment]
Quick update on trying this on Windows:
I still haven't been successful installing the `Rcplex` package, but two bits of good news:
1. The `cplex` branch can be installed and used on Windows without issues.
2. The `cplex` branch package checks work and I don't get any errors.

Unless you want to explore the `cplexAPI` package at this point, I'd say we could merge the pull request back into the master branch.

**Comment by jeffreyhanson** [comment]
Ok, just to clarify, were you able to install cplexAPI on Linux and Windows? If so, maybe I should re-implement this using cplexAPI instead of Rcplex?

**Comment by ricschuster** [comment]
I was able to install `cplexAPI` on both Windows and Linux. Going with `cplexAPI` would be great, but maybe its me messing something up with `Rcplex`. `cplexAPI` does seem to have active development though, so might be worth it?

**Comment by jeffreyhanson** [comment]
Ok - I'll have a look into cplexAPI then and see what I can do. I'll make a new branch and let you know when it's ready?

**Comment by ricschuster** [comment]
Great!
Thanks Jeff!

**Pull request merged**
