### PR TITLE
Add CPLEX solver, via cplexAPI

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR adds support for generating solutions using IBM CPLEX. Unlike https://github.com/prioritizr/prioritizr/pull/160, it uses the cplexAPI R package (which seems easier to install and also provides more control over the solver). @ricschuster, could you please try installing this branch and see if it works for you?

### CODE REVIEW

**Comment by ricschuster** [comment]
Awesome! Thanks very much for this.
Compiled and installed without issue on my system.
Currently running through the benchmark analysis we did here https://peerj.com/articles/9258/ to see how CPLEX performs.

Having issues installing cplexAPI on my Windows VM. Might try a different machine.

**Comment by jeffreyhanson** [comment]
Awesome! Great to hear its working now. Excellent - thank you very much for running the benchmarks with CPLEX - I'm really curious to see how they turn out!

**Comment by ricschuster** [comment]
Me too. So far Gurobi and CPLEX are very close, but I've only completed scenarios up to 37000 pu's. Will be interesting to see if they diverge at more complex problems.
And I'm really curious to see what happens with `add_boundary_penalties`.

As for this pull request, I think we can merge it back into master

**Comment by jeffreyhanson** [comment]
Yeah - it would be great if CPLEX performed really well with boundary penalties. 

Ok great. Before we merge the branch, could you take a look at something specifically (if you haven't already)? Since cplexAPI package doesn't provide a single function  convenience function for solving MILPs (unlike Gurobi, e.g.  `gurobi::gurobi`), I had to write a function like this for prioritizr. Specifically, [I wrote a `cplex` function to do this](https://github.com/prioritizr/prioritizr/blob/cplexapi/R/add_cplex_solver.R#L179-L258) and [wrote some unit tests to verify that it gives the same answers as SYMPHONY](https://github.com/prioritizr/prioritizr/blob/cplexapi/tests/testthat/test_cplex.R). Could you take a look at this `cplex` function and the tests and let me know what you think? I included tests to check that it works for LP, ILP, and MILP problems and various functionality (e.g. variable bounds). These tests pass on my system - but can you think any extra tests worth including here to make sure the CPLEX inferface is working correctly?

**Comment by ricschuster** [comment]
As far as I can tell both the function and tests are sound. I've worked my way through the function and I think everything works as it should.

Tests for LP, ILP and MILP make sense to me and should be comprehensive enough to make sure the CPLEX interface is working appropriately.

**Comment by jeffreyhanson** [comment]
Ok - awesome! Let's merge the branch then? Unless you can think of anything extra?

**Pull request merged**
