### PR TITLE
Documentation and error message tweaks

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR contains various documentation and error message tweaks (fixing #176). Specifically, it adds (1) more precise documentation to the evaluation functions regarding the solution format, (2) examples for using `sf` class spatial data importance functions, and (3) provides more helpful error messages if invalid solutions are provided (e.g. they contain the extra columns). It also fixes a few minor typos in the documentation, and adds a method for calculating the Ferrier importance scores with `sf` planning unit data (I think I forgot to add this previously). 

@ricschuster, when you get a chance, could you please take a look? The main changes are in the following files:
  * R/eval_cost_summary.R: this contains the Solution format section text that is re-used for other functions. Can you check if it makes sense and doesn't have any typos?
  * R/planning_unit_solution_status.R: this contains checks used by all the `eval_` functions to verify that solution data are in the right format. Are the error messages (i.e. `msg` arguments in the `assertthat::assert_that` calls) helpful?
  * R/eval_rare_richness_importance.R, R/eval_ferrier_importance.R, R/eval_replacement_importance.R: these functions have been refactored to use the `planning_unit_solution_status` function so that all `eval_` functions use the  `planning_unit_solution_status` function to handle solution data. I have also added an example using `sf` data to each of these functions. Although these functions all pass the unit tests (which largely remain unchanged), could you please take a quick look and see if they still work for you?

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
The CI checks for verifying CRAN's checks all pass now. The code coverage check is the only one failing, but there's not much I can do about that since (to my knowledge) we can't increase coverage without actually solving problems in the example sections.

**Comment by jeffreyhanson** [comment]
I've been updating prioritizr with a new objective function for the SCP connectivity project. Specifically, this objective function aims  to minimize the largest target shortfall (rather than the sum of the shortfalls per `add_min_shortfall` function). It's basically a "proper" implementation of the min max shortfall stuff we've been chatting about. Note that this objective function is not compatible with weights (since I couldn't figure out a consistent way to do this with the other obj functions that use weights).
The main changes are in:

```
* R/objectives.R (added it to the list of obj funs + added an example).
* R/add_min_largest_shortfall.R (main implementation)
* src/rcpp_apply_min_largest_shortfall_objective (underlying C++ code)
* R/compile.R (updating `compile()` so it throws a warning when you try to use it with weights)
* tests/testthat/test_add_min_largest_shortfall.R (unit tests)
* tests/testthat/test_compile.R (check that using this new obj fun with weights throws a warning)
* vignettes/prioritizr.Rmd (added the new obj function to the list of all such functions)
```

**Comment by ricschuster** [comment]
Thanks very much Jeff! This looks awesome!
I will try to have a look at this tomorrow or my Thursday at the latest.

**Comment by jeffreyhanson** [comment]
Ok excellent - thanks! Once we've merged this into the master branch, I'll start implementing #178.

**Comment by ricschuster** [comment]
Awesome!
I better get to it than.

**Comment by jeffreyhanson** [comment]
Thanks - no rush though :)

**Comment by ricschuster** [comment]
I went through the pull request files and aside from a small typo/word issue it all looks good to me.

If you are happy with it, I'd say we are ready to merge this back into master.

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much! Did you get a chance to play around with the new `add_min_largest_shortfall_objective`?

**Comment by ricschuster** [comment]
Just with the example datasets, but looks all good to me.

I can also use some "real" data with it as well later in the week, if you think its helpful.

**Comment by jeffreyhanson** [comment]
Ok great! Thanks for the offer, but I don't it needs additional testing with a real dataset. I'll merge the PR now then.

**Pull request merged**
