### PR TITLE
Fix #333, #334

### LINKED ISSUE #333: binary_stack() fails when the input layer contains zeros
Here's a reprex:

```
# create raster with categorical values
x <- terra::rast(matrix(c(1, 2, 3, 0, NA, 1), nrow = 3))

# convert to binary stack
y <- binary_stack(x)
#> Error: [subset] invalid name(s)
```

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR provides the following minor bug files and updates:

- Fix bug in `add_max_utility_objective()` that caused the optimization process to throw an error about problem infeasibility when using feature data that contain negative values (#334). Thanks to \@hannahmp for bug report. This  impacts the files: 
    - `R/add_max_utility_objective.R`, 
    - `src/rcpp_apply_max_utility_objective.cpp`, 
    - `tests/testthat/test_add_max_utility_objective.R`, 
    - `R/ConservationProblem-class.R`, 
    - `tests/testthat/test_problem.R`, 
    - `tests/testthat/test_problem_negative.R `
- Fix bug in `presolve_check()` that would cause it to erroneously suggest that many planning units don't have any feature data associated with them. This bug was caused when the feature data contained relatively large, negative values. This impacts the files: 
    - `R/presolve_check.R`, 
    - `tests/testthat/test_presolve_check.R`
- Fix bug in `binary_stack()` that caused it to throw an error when working with raster data containing zeros (#333). This impacts the files: 
    - `R/binary_stack.R`, 
    - `R/binary_stack.R`
- Update `compile()` so that it throws an error when using the expanded version of a problem formulation with negative feature values. This is because the expanded version of the problem formulations are not compatible with negative feature values. Currently, the expanded version of the problem formulation is only required when using `add_feature_contiguity_constraints()`. This impacts the files: 
    - `R/compile.R`, 
    - `tests/testthat/test_compile.R`
- Fix bug in `add_absolute_targets()` where it would not throw a warning to the user know that a problem already had targets defined, and so adding the new targets would override the existing targets defined for the problem. This impacts the files: 
    - `R/add_absolute_targets.R`,
    - `tests/testthat/test_add_absolute_targets.R`,
    - ` R/add_manual_targets.R`
- Fix bug in `as.ZonesRaster` that resulted in an error when trying to convert a `SpatRaster` zones object (i.e., a `zones` object with _terra_ package data) into `Raster` zones object (i.e., a `zones` object with _raster_ package data). This impacts the files: 
    - `R/as.R`, 
    - `tests/testthat/test_zones.R`
- Fix bug in `write_problem()` needlessly printing messages about the  _gurobi_ package not being installed when the function is trying to  automatically determine which solver to use (i.e., when using  `solver = NULL`) and the package is not is available. This impacts the files: 
    - `R/write_problem.R`
- Fix bug in `branch_matrix()` where it would not automatically convert object to the `phylo` class in the _ape_ package. This impacts the files: 
    - `R/branch_matrix.R`, 
    - `tests/testthat/test_branch_matrix.R`
- Update warning messages so that they now indicate which function threw the warning message (using `rlang::warn()`). This impacts the files: 
    - `R/cli.R`, 
    - `R/assertions.R`, 
    - `tests/testthat/test_cli.R`
- Additional tests to improve test coverage. This impacts the files: 
    - `src/rcpp_add_rij_data.cpp`,
    - `src/rcpp_apply_feature_contiguity_constraints.cpp`, 
    - `src/rcpp_ferrier_score.cpp`, 
    - `tests/testthat/test_add_linear_constraints.R`,
    - `tests/testthat/test_add_linear_penalties.R`, 
    - `tests/testthat/test_marxan_connectivity_data_to_matrix.R`

### CODE REVIEW

**Review by sandra-neubert — COMMENTED** [review]
Thanks, Jeff!

A quick summary for all the changes:
- changes in `add_max_utility_objective()`: looks good to me, tests are working
- changes in `presolve_check()`: looks good to me, tests are working
- changes in `binary_stack()`: looks good to me, tests are working; 0 layer might be a bit confusing to some based on the example (subplot 3) in `binary_stack()`. Maybe some more explanation would be helpful?
- changes in `compile()`: looks good to me, tests are working
- changes in `add_absolute_targets()` and `add_manual_targets()`: looks good to me, tests are working
- changes in `as.ZonesRaster`: looks good to me, tests are working
- changes in `write_problem()`: works without throwing a warning when gurobi package is not installed (but other solvers are). 
- changes in `branch_matrix()`: looks good to me, tests are working
- changes with warning messages: looks good to me, tests are working
- testing updates work well

**Comment by jeffreyhanson** [comment]
Awesome - thanks very much @sandra-neubert! Yeah, that's a really good point about the `binary_stack()` function. To address this, what do yout think about including a `drop_zero` parameter to the function?. If `TRUE` (the default), then a layer indicating the presence/absence of zeros will not be included in the output. Otherwise if `FALSE`, then it will prodcue a layer for the zeros in the input dataset.

**Comment by sandra-neubert** [comment]
@jeffreyhanson that sounds great! I think that would avoid confusion for those who don't need this layer but makes it easy to find for those who want to include it. Happy to help implement this.

**Comment by jeffreyhanson** [comment]
Ok awesome! Yeah, if you've got time to implement this, that'd be really helpful - thank you! I completely understand if you've got other stuff to focus on - just let me know? I'm swamped this week, so I probably wouldn't get to this until near the end of next week.

**Comment by sandra-neubert** [comment]
Yes, no worries, happy to have a go at it this week!

**Comment by jeffreyhanson** [comment]
I've got some time this afternoon to work on this, so I'll have a go and see what I can do.

**Comment by jeffreyhanson** [comment]
@sandra-neubert, I've just pushed some commits to (i) fix #339, and (ii) add in a new parameter for `binary_stack()` so that empty layers can be excluded if desired. Note that the default behaivor is still to keep empty layers to retain backwards compatibility.

**Comment by sandra-neubert** [comment]
Looks good to me @jeffreyhanson and testing is working.

**Comment by jeffreyhanson** [comment]
Brilliant - thank you @sandra-neubert!

**Pull request merged**
