### PR TITLE
version 5

### PR DESCRIPTION
**Pull request by jeffreyhanson**
I've just pushed all the fixes/changes for version 5, so I'm now opening this pull request. @ricschuster and @mstrimas, could you please take a look when you get a chance? In future, I think it might be better to have much smaller pull requests so it's easier to get through thing. Here are all the relevant issues here: #6, #130, #131, #132, #133, #134. Each issue should contain a list of the relevant files. I think I mentioned this earlier, but you might want to come up with a plan (e.g. allocate different issues to each of you, or have one person looking at a specific issue at a time to avoid merge conflicts). Please let me know if anything's not clear or if you have any questions?

Also, I haven't rebuilt the readme and package website to reduce the number of changed files. Once you think the merge is ready to go, I can rebuild the docs right before we merge it.

### CODE REVIEW

**Comment by mstrimas** [comment]
Sounds like @ricschuster intends to look through all the code to familiarize himself with it. I don't have time for that at the moment, but I will at least take a look at the sf and velox/exactextractr components of this pull request.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson!
I agree, smaller pull requests in the future would probably be a good idea, but this all looks awesome. Thanks very much for pulling this all together!

@mstrimas yes, my plan was to work through it all. I can hold off on the sf and velox/exactextractr components if you'd like, or we can just coordinate as we go along.

**Comment by jeffreyhanson** [comment]
Ok sounds great - thank you very much @ricschuster and @mstrimas

**Comment by jeffreyhanson** [comment]
Just a heads up, @mstrimas and @ricschuster, I finally got the automated checks working for v5

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson!

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much for reviewing the code @mstrimas!

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson for all your work on this and @mstrimas for reviewing!
Everything is good on my end too. Should I 'Merge pull request' now?
(Sorry, first time for a pull request for me)

**Comment by jeffreyhanson** [comment]
Brilliant - thank you very much @ricschuster! Before we merge the pull request, I would like to update the pkgdown website with the new documentation and also fix the continuous integration tests that appear to be failing again. Once I've done that, I'll let you know and you can merge pull request?

**Comment by ricschuster** [comment]
@jeffreyhanson sounds good. Just let me know when you are done and I can merge the pull request.

**Comment by ricschuster** [comment]
AppVeyor passes now.

Travis Linux R:release too.
R:devel times out 

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Mac R:release errors, but that is probably something not too hard to fix (I hope).

Any ideas about the R:devel and R:release difference?

**Comment by ricschuster** [comment]
@jeffreyhanson looks like the OSX issue might be related to the following from the [Travis log](https://api.travis-ci.org/v3/job/673490227/log.txt):

Cannot find SYMPHONY libraries and headers.

See <https://projects.coin-or.org/SYMPHONY>.

ERROR: configuration failed for package â€˜Rsymphonyâ€™

* removing â€˜/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rsymphonyâ€™

**Comment by jeffreyhanson** [comment]
@ricschuster, maybe - but this warning is also present in the most recent passing build log(https://travis-ci.org/github/prioritizr/prioritizr/builds/663305720). I suspect the issue might be related this message in the build log:

```
  Assertion failed: (0), function query, file ../../../../src/geos-3.7.2/src/index/strtree/AbstractSTRtree.cpp, line 293.
```

So, I've tried commenting out the functions where we call the experimental `rgeos::gUnarySTRtreeQuery` function to see what happens.

**Comment by jeffreyhanson** [comment]
Yeah, that's the issue - the build just passed on [Mac OSX](https://travis-ci.org/github/prioritizr/prioritizr/jobs/673629979)

**Comment by jeffreyhanson** [comment]
I'll properly fix the tests now so that they are active on Linux and Windows, but disabled for OSX.

**Comment by jeffreyhanson** [comment]
There's still an issue with Linux R-Devel though

**Comment by ricschuster** [comment]
> Yeah, that's the issue - the build just passed on [Mac OSX](https://travis-ci.org/github/prioritizr/prioritizr/jobs/673629979)

Great to hear!

> There's still an issue with the Travis Linux R-Devel checks though

I wonder if we should try [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)

**Comment by jeffreyhanson** [comment]
I managed to track down the issue after one of my packages starting failing R-devel Travis checks too. The reason is that R-devel now runs example code wrapped in `\donttest` when checking packages (see http://developer.r-project.org/blosxom.cgi/R-devel/2020/03/20#n2020-03-20). Do you know what  the correct procedure is for including examples that should not be run on CRAN now? I'll try asking the ROpenSci slack group for advice.

**Comment by ricschuster** [comment]
That sounds promising. Unfortunately, I have no idea about the correct procedure for including examples that should not be run on CRAN now.

**Comment by jeffreyhanson** [comment]
Ok, my understanding is that R-Devel by default will now run `\donttest` code in examples unless (1) the option `_R_CHECK_DONTTEST_EXAMPLES_` is set to `FALSE` or (2) the check is run with the `-as-cran` argument. Since CRAN/WinBuilder run checks with `as-cran`, this means that the code in `\donttest` will not be run on these platforms. However, our Travis checks do not use `-as-cran` -- to perform additional checks not checked on CRAN -- and so we should set the 1_R_CHECK_DONTTEST_EXAMPLES_` parameter to FALSE for our Travis checks. I've just updated the travis config file with this setting, so hopefully this should address the R-devel checks failing.

**Comment by ricschuster** [comment]
Sounds great! Just checked Travis, both Linux builds work now. OSX is still throwing an error though.

**Comment by jeffreyhanson** [comment]
Ok, I'll take a look and see what I can do.

**Comment by ricschuster** [comment]
Looks like all Travis builds passed now. @jeffreyhanson do you think we are ready to merge the pull request back into master?

**Comment by jeffreyhanson** [comment]
@ricschuster, almost ready. I'm just making sure that prioritizr will work under the new versions of PROJ (v 7), sf (0.9.*), and rgdal (1.5.*). I'm hoping we can merge this later today.

**Comment by jeffreyhanson** [comment]
@ricschuster, I've finished updating the code to avoid issues with PROJ7. If the continuous integration tests that are still running pass, please feel free to merge the pull request if/when you're happy with it?

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson! 
Great to hear that you were able to sort out the PROJ7 issues.
Travis tests passed, so I will merge the pull request.
If you are happy with this, I can submit to CRAN as well.

**Comment by jeffreyhanson** [comment]
Excellent! Did we want add the Ferrier functionality before submitting to CRAN?

**Comment by jeffreyhanson** [comment]
Also, I just remembered that I should rebuild the docs again - let me do this before submitting to CRAN.

**Comment by ricschuster** [comment]
We could certainly add Ferrier before submitting to CRAN. What about version number? Should probably push past 5.0.0 if we do that?

**Comment by jeffreyhanson** [comment]
Yeah, I'll open another pull request for the Ferrier metric with version 5.0.0.1 and see if I can get it finished sometime this week. I suggest that the CRAN version be released as 5.0.1?

**Comment by ricschuster** [comment]
Sounds great! 
Lets do that.

**Comment by jeffreyhanson** [comment]
Ok - excellent!

**Comment by jeffreyhanson** [comment]
Looks like AppVeyor tests just failed, but it seems that it's due to AppVeyor problems not any changes to the prioritizr code.

**Comment by ricschuster** [comment]
Weird.

**Pull request merged**
