### PR TITLE
Remove invalid reference to sf and include example

### LINKED ISSUE #195: Creating a conservation problem with sf object and data.frames
Firstly, thanks so much @jeffreyhanson (and all contributors) for the wonderful package and documentation. It's an amazing achievement. 

However, I am having trouble using the new `sf` capability when creating the `problem` object. If I interpret the vignette correctly (https://prioritizr.net/reference/problem.html) I should be able to create a problem where `x` is an `sf` object, and `features` and `rij` are data frames.  
From the vignette the 3rd option under features suggests when `x` is an sf-object, I can use data frames for `features`: 
         "x = Spatial-class, or **x = sf::st_sf()**, or x = data.frame, or x = numeric vector, or x = matrix: **y = data.frame object** containing the names of the features.

I have created a small reprex below which uses `sim_pu_sf` from prioritizr datasets and then I create appropriate data frames for `rij` and `features`. However, I get the error: _Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘problem’ for signature ‘"sf", "data.frame"’_

Apologies if I am missing something obvious, but I can't get this to work, and I *think* the vignette suggests I should be able to, although I acknowledge there are no examples of sf + data frames so perhaps its not ....

I have updated all my packages, included prioritizr to the latest GitHub version as per the top of the reprex.

Any help would be appreciated.

```
library(sf)
library(prioritizr)
# packageVersion("sf")
# [1] ‘0.9.8’
# packageVersion("prioritizr")
# [1] ‘7.0.1.2’

data(sim_pu_sf) # load example PUs data from prioritizr
sim_pu_sf$id = 1:90 # assign PU id number. Not sure this is needed but it matches pu in rij (below)

features = data.frame(id = 1:3, name = c("A", "B", "C")) # Create dummy features as a data frame

# Create rij for each feature and then combine.
set.seed(23)
rij_1 <- data.frame(pu = ceiling(runif(50, 0, 89)), species = 1, amount = 100)
rij_2 <- data.frame(pu = ceiling(runif(20, 0, 89)), species = 2, amount = 100)
rij_3 <- data.frame(pu = ceiling(runif(20, 0, 89)), species = 3, amount = 100)
rij <- rbind(rij_1, rij_2, rij_3)
rm(rij_1, rij_2, rij_3)

# Check all classes are correct as per the documentation
class(sim_pu_sf) # should be sf
class(features) # should be data.frame
class(rij) # should be data.frame

p1 <- prioritizr::problem(x = sim_pu_sf, features = features, rij = rij, cost_column = "cost")
# results in 
# >Error in (function (classes, fdef, mtable)  : 
# >unable to find an inherited method for function ‘problem’ for signature ‘"sf", "data.frame"’
```

### PR DESCRIPTION
**Pull request by jaseeverett**
@jeffreyhanson I have removed the invalid reference to sf object in the help. fixes #195 

I also included a new example (p7), which specifically demonstrates the use of the sf object with features included. I hope this is appropriate and helpful. I tried to get the format correct, but there may be corrections needed.

Apologies for the delay in this.

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Awesome - thanks so much @jaseeverett! I'll try and take a closer look at this today.

**Comment by jeffreyhanson** [comment]
Sorry, this might take a bit longer than I originally expected. For some weird reason, all the examples images in the package website aren't plotting correctly when I rebuild the package website on my computer.

**Comment by jaseeverett** [comment]
No worries. Let me know if you need me to do anything else.  I'm pretty good in R, but have no experience with building packages. We are using this a lot in our group @ UQ, so happy to help where I can.

**Comment by jeffreyhanson** [comment]
Thanks for the offer. I think this is due to something on my computer (e.g. I've updated an R package or system library, and something's no longer working correctly), but I'll let you know if I need a hand.

**Comment by jeffreyhanson** [comment]
@jaseeverett, I've just pushed a commit to the PR to tweak your example and rebuild the site. Specifically, the example now includes code showing how to (1) calculate the amount of each species within each planning unit, (2) add columns to the Spatial/sf objects, and (3) build the problems. I thougt this might be more helpful than just simulating the data - what do you think? If you have any further ideas for improving it, please feel free to make any further tweaks?

**Comment by jeffreyhanson** [comment]
I think the CI build failures are not related to this PR  -- I think one of prioritizr's dependencies might have updated and this is causing issues -- so we can ignore them for this PR. I'll make another PR to address the build failures.

**Comment by jaseeverett** [comment]
Great @jeffreyhanson. Creating the data from `rij_matrix` is a great approach. I wasn't aware of that function. I don't have anything else to add.

**Comment by jeffreyhanson** [comment]
Awesome - thanks! I'll merge the PR now then.

**Pull request merged**
