### PR TITLE
Ferrier irreplaceability scores

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This pull request is to add functionality to compute irreplaceability scores for planning units selected in a solution following the method outlined in Ferrier _et al._ (2000). If you're not too busy, could you please take a look at it @mstrimas and @ricschuster? I completely understand if you're too busy at the moment - just let me know.

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Also, note that I haven't rebuilt the package website in this branch yet so it's easier to see what's changed from the master branch.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson!
I will do my best to review this pull request this week.

**Comment by ricschuster** [comment]
Sorry it took longer than I'd hoped for to review this. Only made 1 tiny change to the code.

I really like the text you added to the Irreplaceability section of the prioritizr vignette. This should be very useful for users I think. Do you think we should add this text to `irreplaceability.R` as well? Could be useful there as well.

**Comment by jeffreyhanson** [comment]
@ricschuster, excellent point! I'll add that to the irreplaceability page.

@mstrimas, were you able to take a look at this PR? I completely understand if you're too busy at the moment?

**Comment by jeffreyhanson** [comment]
Also, I've pushed a couple of commits to the master branch to fix the travis/appveyor checks. These fixes aren't in this PR so it still says that the checks are failing - but if/when it gets merged with the master branch it should all work.

**Comment by ricschuster** [comment]
Thanks for confirming Jeff! That's what I thought.

**Comment by ricschuster** [comment]
@jeffreyhanson I think @mstrimas might be busy at the moment. What do you think about merging this pull request and getting things ready to be pushed to CRAN?

**Comment by mstrimas** [comment]
Sorry y'all totally missed this until just now, completely swamped with work at the moment, so won't have time to look at this PR. I concur with Richard, just go ahead merge this thing and submit to CRAN!

**Comment by jeffreyhanson** [comment]
No worries @mstrimas. I'll merge the pull request now, and then update the package site on the master branch.

**Pull request merged**
