### PR TITLE
Add CBC solver + update solver documentation

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR adds support for the CBC solver via the rcbc R package (#178). It also updates the documentation for the solvers to provide (1) default values for all parameters, (2) better installation instructions, and (3) references for the software underlying each solver.

@ricschuster, when you get a chance, could you please take a look? Disappointingly, CBC doesn't seem to provide information on how much progress has been made towards solving a given problem (e.g. optimality gap for current best solution). Additionally, I couldn't work out how to silence CBC when running it (e.g. the parameters for logging do not disable output entirely, and functions like `capture.output()` and `suppressMessages()` do not seem to work to hiding outputs) so it will always print text to screen when solving a problem (i.e. even when `verbose = FALSE`).

Also, I haven't really tested the performance of the CBC solver but it seems pretty decent for the example datasets. If it's not too much of a hassle, could you try running it with your benchmarks for the PeerJ paper to see how it compares with Rsymphony?

The main files that have been updated include:
* R/add_default_solver.R
* tests/testthat/test_add_cbc_solver.R
* R/add_cbc_solver
* R/solvers.R (only documentation changes)
* R/add_gurobi_solver.R (only documentation changes)
* R/add_cplex_solver.R (only documentation changes)
* R/add_rsymphony_solver.R  (only documentation changes)
* R/add_lpsymphony_solver.R (only documentation changes)
* vignettes/prioritizr.Rmd (now includes CBC solver)
* vignettes/saltspring.Rmd (now includes CBC solver example)

### CODE REVIEW

**Comment by ricschuster** [comment]
Awesome!
Will setup the benchmarking now and do a review of the pull request on Monday.
What do you think we should set the SYMPHONY gap to?
Currently we have gap * 'cost of Gurobi solutions' in that paper. I'm keeping for now, but if you think we should change that, let me know.

**Comment by ricschuster** [comment]
@jeffreyhanson the CBC solver is awesome!
I was benchmarking against SYMPHONY at first but quickly realized that its much faster than SYMPHONY.
What I've done instead was benchmark against Gurobi.
The results so far are amazing!

Below a figure showing the run time differences for the PeerJ scenarios with 
n_features == 72 & n_pu == 148510

The red line is CBC and its actually faster than Gurobi for this min set configuration!
The equation for the points on the figure are:
(time - time_gur)/time_gur * 100

You might have just solved our main issue with prioritzr for reasonably sized problem Jeff!
If CBC holds up for other objective functions and penalty functions too, we would be golden with an open source solver.

What do you think?

image

**Comment by jeffreyhanson** [comment]
Wow - that's awesome! Thank you very much for looking into this. I can't really take any credit for this though - I just wrote a wrapper for rcbc. How does the objective value of the solutions from CBC compare with Gurobi? E.g. could you make a graph like Figure 1a in your [PeerJ paper](https://peerj.com/articles/9258/)?  I'll update the documentation and `add_default_solver()` to recommend this as the FOSS solver.

**Comment by jeffreyhanson** [comment]
Also, I wonder if the reason Gurobi is slower here is because it has an intensive pre-solve step? For example, if you set `presolve = -1` so that Gurobi automatically determines pre-solve intensity, I wonder if we might see more similar run times? Also, did you run this with `threads = 1` or something higher?

**Comment by jeffreyhanson** [comment]
I wonder if it's worth following up on the rcbc repo to see if there's anything we can do to help get it on to CRAN? I think having it available on CRAN would make it a lot easier for users to use the CBC solver.

**Comment by jeffreyhanson** [comment]
Also, I don't know what we should use for the SYMPHONY gap. Before I can be certain, I would need clarification on exactly how the `gap_limit` parameter works for SYMPHONY. Unfortunately, I haven't heard back yet from the issue that I posted on the repository. I'll try sending out an email on the SYMPHONY emailing list tomorrow to see if we can clarification from there. In the meantime, I would suggest setting the gap as `100 * gurobi_gap` (e.g. if the gurobi gap is 0.1, then set the SYMPHONY gap as 10).

**Comment by jeffreyhanson** [comment]
Also, if it's not too much of a hassle, could you try running the benchmarks with the boundary penalties added? I feel like this would be a better test for more real-world conservation planning scenarios.

**Comment by ricschuster** [comment]
> 
> 
> Wow - that's awesome! Thank you very much for looking into this. I can't really take any credit for this though - I just wrote a wrapper for rcbc. How does the objective value of the solutions from CBC compare with Gurobi? E.g. could you make a graph like Figure 1a in your [PeerJ paper](https://peerj.com/articles/9258/)? I'll update the documentation and `add_default_solver()` to recommend this as the FOSS solver.

You are too modest. You thought about CBC and implemented it into prioritizr. This will make a huge difference I think.

Here an equivalent of Figure 1a. You can see the results are essentially identical for cost. 
The gap used for both was 0.001.
image

**Comment by ricschuster** [comment]
> 
> 
> Also, I wonder if the reason Gurobi is slower here is because it has an intensive pre-solve step? For example, if you set `presolve = -1` so that Gurobi automatically determines pre-solve intensity, I wonder if we might see more similar run times? Also, did you run this with `threads = 1` or something higher?

I've used `threads = 10` for both.
Will adjust `presolve` and `threads` and run again.

**Comment by ricschuster** [comment]
> 
> 
> I wonder if it's worth following up on the rcbc repo to see if there's anything we can do to help get it on to CRAN? I think having it available on CRAN would make it a lot easier for users to use the CBC solver.

I think that's a great idea. Would be really good to have the rcbc package on CRAN.

**Comment by ricschuster** [comment]
> 
> 
> Also, I don't know what we should use for the SYMPHONY gap. Before I can be certain, I would need clarification on exactly how the `gap_limit` parameter works for SYMPHONY. Unfortunately, I haven't heard back yet from the issue that I posted on the repository. I'll try sending out an email on the SYMPHONY emailing list tomorrow to see if we can clarification from there. In the meantime, I would suggest setting the gap as `100 * gurobi_gap` (e.g. if the gurobi gap is 0.1, then set the SYMPHONY gap as 10).

Too bad that nobody has replied to the issue yet. Hopefully sending an email to the mailing list will get a response.
Sounds good re: 100 * gurobi_gap for now.

**Comment by ricschuster** [comment]
> 
> 
> Also, if it's not too much of a hassle, could you try running the benchmarks with the boundary penalties added? I feel like this would be a better test for more real-world conservation planning scenarios.

Will do that after the re-runs with `threads = 1` and `presolve = -1` are done.
Fingers crossed CBC does well here too.

**Comment by ricschuster** [comment]
> > Also, I wonder if the reason Gurobi is slower here is because it has an intensive pre-solve step? For example, if you set `presolve = -1` so that Gurobi automatically determines pre-solve intensity, I wonder if we might see more similar run times? Also, did you run this with `threads = 1` or something higher?
> 
> I've used `threads = 10` for both.
> Will adjust `presolve` and `threads` and run again.

Results don't really change with the new parameters. I did set the CBC solver as default, so the figure looks a bit different.
image

**Comment by jeffreyhanson** [comment]
I've just pushed a new commit in a moment. This commit updates the documentation for the solvers to recommend using CBC over the SYMPHONY-based solvers. It also now recommends lpsymphony over Rsymphony, since lpsymhony uses parallel processing. Previously, the documentation didn't really make it clear that these the SYMPHONY-based solvers had different performance. I've also updated the default solver to use the following order for selecting solvers (from highest to lowest preference): gurobi, cplex, CBC, lpsymphony, and Rsymphony.

The main files are:
* R/add_default_solver.R
* R/add_cbc_solver
* R/solvers.R (only documentation changes)
* R/add_rsymphony_solver.R (only documentation changes)
* R/add_lpsymphony_solver.R (only documentation changes)
* tests/testthat/test_add_gurobi_solver.R (added test to ensure solutions meet various constraint senses).
* tests/testthat/test_add_cplex_solver.R (added test to ensure solutions meet various constraint senses).
* tests/testthat/test_add_rsymphony_solver.R (added test to ensure solutions meet various constraint senses).
* tests/testthat/test_add_lpsymphony_solver.R (added test to ensure solutions meet various constraint senses).
* tests/testthat/test_add_cbc_solver.R (added test to ensure solutions meet various constraint senses).

**Comment by jeffreyhanson** [comment]
Interesting - thank you very much for generating those additional figures! It's looking like CBC could indeed be good open source alternative to Gurobi. I'm looking forward to seeing how it compares with Gurobi when using the boundary penalties.

**Comment by ricschuster** [comment]
> 
> 
> Interesting - thank you very much for generating those additional figures! It's looking like CBC could indeed be good open source alternative to Gurobi. I'm looking forward to seeing how it compares with Gurobi when using the boundary penalties.

I'm looking forward to seeing those results as well.
Started them now. Should be done tomorrow morning.

**Comment by jeffreyhanson** [comment]
Awesome - can't wait!

**Comment by ricschuster** [comment]
I've finally made it all the way through the PR changes and think its ready to be merged back into master.
The addition of the CBC solver is really exciting!

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much! I'll merge it now then

**Pull request merged**
