### PR TITLE
add highs solver (fix #250)

### LINKED ISSUE #250: add new solver to support HiGHS software
HiGHS is a FOSS optimization software that can solve MILPs (see https://highs.dev/). I just noticed that a highs R package was recently published on CRAN (https://cran.r-project.org/package=highs). It would be great to add a new solver function to support this software, and possibly re-run the benchmarks vignette to see how it compares.

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR adds support for the HiGHS solver with a new `add_highs_solver()` function (addressing #250). @ricschuster, when you get a chance, could you please (i) update the benchmark vignette with the new results for the highs solver, and (ii) review the other changes in this PR?

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, please ignore the failing windows build - that's due to some random initialization failures that aren't related to this PR.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson !
The code looks good and I have added the updated benchmark vignette as well.
macOS-latest checks are failing now. Do you happen to have an idea about what's going on there?

**Comment by jeffreyhanson** [comment]
Awesome - thanks! Sure, I'll try and get to this on Wednesday

**Comment by jeffreyhanson** [comment]
@ricschuster, sorry for taking so long with this. I've added some minor tweaks to the vignette and a paragraph explaining the main columns in the `benchmark_results` table. When you get a chance, could you please take a look? Once/if you're happy with it, I'll then remake the website the merge the PR.

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson !
Looks good to me. I'm happy for you to merge the PR when ready.

**Pull request merged**
