### PR TITLE
Fix R-devel warnings

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR is to fix the same issues discussed in prioritizr/oppr#17. It also contains a few extra fixes to the documentation (e.g. typos and grammar). When you get a chance, @ricschuster could you please take a look?

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, when you get a chance to look at this, I think its ready for you now.

**Comment by ricschuster** [comment]
Hi @jeffreyhanson 
Sorry for being so slow with this. Been swamped with other stuff.
I haven't looked at all the functions/documentation because there are so many, but the ones I looked at seemed consistent with what was there before the R-devel warnings.

I haven't merged the pull request back into master yet, because there were some Travis errors.

**Comment by jeffreyhanson** [comment]
No worries @ricschuster. Ok - excellent - thank you! I'll fix the Travis error and then merge into master?

**Comment by ricschuster** [comment]
Sounds great!
Thanks very much @jeffreyhanson

**Comment by jeffreyhanson** [comment]
Excellent - seems like the Travis builds were failing due to homebrew install issues on OSX. The CI checks are passing now, so I'll merge the PR.

**Pull request merged**
